/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.AccessLog;
import jp.co.kunisys.member.query.tables.AdToJapaneseYear;
import jp.co.kunisys.member.query.tables.AnalysisBusho;
import jp.co.kunisys.member.query.tables.AnalysisCustomer;
import jp.co.kunisys.member.query.tables.AnalysisDate;
import jp.co.kunisys.member.query.tables.AnalysisDaywork;
import jp.co.kunisys.member.query.tables.AnalysisGenka;
import jp.co.kunisys.member.query.tables.AnalysisJobInfo;
import jp.co.kunisys.member.query.tables.AnalysisMember;
import jp.co.kunisys.member.query.tables.AnalysisProject;
import jp.co.kunisys.member.query.tables.AnalysisProjectInfo;
import jp.co.kunisys.member.query.tables.AnalysisProjectMemberMonthlySummary;
import jp.co.kunisys.member.query.tables.AnalysisProjectMonthlySummary;
import jp.co.kunisys.member.query.tables.AnalysisProjectSummary;
import jp.co.kunisys.member.query.tables.AnalysisUserInfo;
import jp.co.kunisys.member.query.tables.AppInfo;
import jp.co.kunisys.member.query.tables.Auth;
import jp.co.kunisys.member.query.tables.AuthAssign;
import jp.co.kunisys.member.query.tables.AuthFunction;
import jp.co.kunisys.member.query.tables.Career;
import jp.co.kunisys.member.query.tables.CareerDetail;
import jp.co.kunisys.member.query.tables.CareerDetailSkill;
import jp.co.kunisys.member.query.tables.Department;
import jp.co.kunisys.member.query.tables.EduBackground;
import jp.co.kunisys.member.query.tables.Gender;
import jp.co.kunisys.member.query.tables.Ipv4AddressManage;
import jp.co.kunisys.member.query.tables.IsmsAccessAuth;
import jp.co.kunisys.member.query.tables.IsmsAccessAuthServerPath;
import jp.co.kunisys.member.query.tables.IsmsAccessAuthUser;
import jp.co.kunisys.member.query.tables.IsmsAsset;
import jp.co.kunisys.member.query.tables.IsmsAssetAssess;
import jp.co.kunisys.member.query.tables.IsmsAssetAssessManage;
import jp.co.kunisys.member.query.tables.IsmsAssetAssessManagePlan;
import jp.co.kunisys.member.query.tables.IsmsAssetAssessManageRisk;
import jp.co.kunisys.member.query.tables.IsmsAssetAssessRisk;
import jp.co.kunisys.member.query.tables.IsmsAssetAssessValue;
import jp.co.kunisys.member.query.tables.IsmsAssetId;
import jp.co.kunisys.member.query.tables.IsmsAssetManagePlan;
import jp.co.kunisys.member.query.tables.IsmsAssetPattern;
import jp.co.kunisys.member.query.tables.IsmsAssetRisk;
import jp.co.kunisys.member.query.tables.IsmsAssetType;
import jp.co.kunisys.member.query.tables.IsmsAssetTypeCategory;
import jp.co.kunisys.member.query.tables.IsmsGreaterManager;
import jp.co.kunisys.member.query.tables.IsmsHardware;
import jp.co.kunisys.member.query.tables.IsmsManagePlan;
import jp.co.kunisys.member.query.tables.IsmsOutsideDoc;
import jp.co.kunisys.member.query.tables.IsmsOutsideMedia;
import jp.co.kunisys.member.query.tables.IsmsSoftware;
import jp.co.kunisys.member.query.tables.IsmsSoftwareUse;
import jp.co.kunisys.member.query.tables.IsmsStore;
import jp.co.kunisys.member.query.tables.IsmsStoreAsset;
import jp.co.kunisys.member.query.tables.IsmsStoreDispose;
import jp.co.kunisys.member.query.tables.IsmsStoreIn;
import jp.co.kunisys.member.query.tables.IsmsStoreOut;
import jp.co.kunisys.member.query.tables.IsmsSystemInfo;
import jp.co.kunisys.member.query.tables.IsmsSystemProject;
import jp.co.kunisys.member.query.tables.IsmsVirtualMachine;
import jp.co.kunisys.member.query.tables.Kubun;
import jp.co.kunisys.member.query.tables.License;
import jp.co.kunisys.member.query.tables.PersonalSkill;
import jp.co.kunisys.member.query.tables.Post;
import jp.co.kunisys.member.query.tables.RelateDepartment;
import jp.co.kunisys.member.query.tables.RelateUser;
import jp.co.kunisys.member.query.tables.School;
import jp.co.kunisys.member.query.tables.Skill;
import jp.co.kunisys.member.query.tables.SkillKind;
import jp.co.kunisys.member.query.tables.TopMessage;
import jp.co.kunisys.member.query.tables.UserAuth;
import jp.co.kunisys.member.query.tables.UserInfo;
import jp.co.kunisys.member.query.tables.UserInfoAppointment;
import jp.co.kunisys.member.query.tables.UserInfoFamily;
import jp.co.kunisys.member.query.tables.UserInfoInsurance;
import jp.co.kunisys.member.query.tables.UserInfoRetire;
import jp.co.kunisys.member.query.tables.UserInfoView;
import jp.co.kunisys.member.query.tables.UserInfoWorkplace;
import jp.co.kunisys.member.query.tables.Workplace;


/**
 * Convenience access to all tables in members
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * アクセス履歴
	 */
	public static final AccessLog ACCESS_LOG = jp.co.kunisys.member.query.tables.AccessLog.ACCESS_LOG;

	/**
	 * 西暦和暦
	 */
	public static final AdToJapaneseYear AD_TO_JAPANESE_YEAR = jp.co.kunisys.member.query.tables.AdToJapaneseYear.AD_TO_JAPANESE_YEAR;

	/**
	 * 分析部署
	 */
	public static final AnalysisBusho ANALYSIS_BUSHO = jp.co.kunisys.member.query.tables.AnalysisBusho.ANALYSIS_BUSHO;

	/**
	 * 分析取引先
	 */
	public static final AnalysisCustomer ANALYSIS_CUSTOMER = jp.co.kunisys.member.query.tables.AnalysisCustomer.ANALYSIS_CUSTOMER;

	/**
	 * 分析日付
	 */
	public static final AnalysisDate ANALYSIS_DATE = jp.co.kunisys.member.query.tables.AnalysisDate.ANALYSIS_DATE;

	/**
	 * 分析稼働時間
	 */
	public static final AnalysisDaywork ANALYSIS_DAYWORK = jp.co.kunisys.member.query.tables.AnalysisDaywork.ANALYSIS_DAYWORK;

	/**
	 * 分析原価
	 */
	public static final AnalysisGenka ANALYSIS_GENKA = jp.co.kunisys.member.query.tables.AnalysisGenka.ANALYSIS_GENKA;

	/**
	 * 分析処理情報
	 */
	public static final AnalysisJobInfo ANALYSIS_JOB_INFO = jp.co.kunisys.member.query.tables.AnalysisJobInfo.ANALYSIS_JOB_INFO;

	/**
	 * 分析社員
	 */
	public static final AnalysisMember ANALYSIS_MEMBER = jp.co.kunisys.member.query.tables.AnalysisMember.ANALYSIS_MEMBER;

	/**
	 * 分析プロジェクト
	 */
	public static final AnalysisProject ANALYSIS_PROJECT = jp.co.kunisys.member.query.tables.AnalysisProject.ANALYSIS_PROJECT;

	/**
	 * 分析プロジェクト情報
	 */
	public static final AnalysisProjectInfo ANALYSIS_PROJECT_INFO = jp.co.kunisys.member.query.tables.AnalysisProjectInfo.ANALYSIS_PROJECT_INFO;

	/**
	 * 分析プロジェクト社員月別集計
	 */
	public static final AnalysisProjectMemberMonthlySummary ANALYSIS_PROJECT_MEMBER_MONTHLY_SUMMARY = jp.co.kunisys.member.query.tables.AnalysisProjectMemberMonthlySummary.ANALYSIS_PROJECT_MEMBER_MONTHLY_SUMMARY;

	/**
	 * 分析プロジェクト月別集計
	 */
	public static final AnalysisProjectMonthlySummary ANALYSIS_PROJECT_MONTHLY_SUMMARY = jp.co.kunisys.member.query.tables.AnalysisProjectMonthlySummary.ANALYSIS_PROJECT_MONTHLY_SUMMARY;

	/**
	 * 分析プロジェクト集計
	 */
	public static final AnalysisProjectSummary ANALYSIS_PROJECT_SUMMARY = jp.co.kunisys.member.query.tables.AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY;

	/**
	 * 分析ユーザ情報
	 */
	public static final AnalysisUserInfo ANALYSIS_USER_INFO = jp.co.kunisys.member.query.tables.AnalysisUserInfo.ANALYSIS_USER_INFO;

	/**
	 * アプリケーション設定マスタ
	 */
	public static final AppInfo APP_INFO = jp.co.kunisys.member.query.tables.AppInfo.APP_INFO;

	/**
	 * 権限
	 */
	public static final Auth AUTH = jp.co.kunisys.member.query.tables.Auth.AUTH;

	/**
	 * 権限割当
	 */
	public static final AuthAssign AUTH_ASSIGN = jp.co.kunisys.member.query.tables.AuthAssign.AUTH_ASSIGN;

	/**
	 * 機能権限
	 */
	public static final AuthFunction AUTH_FUNCTION = jp.co.kunisys.member.query.tables.AuthFunction.AUTH_FUNCTION;

	/**
	 * 業務経歴
	 */
	public static final Career CAREER = jp.co.kunisys.member.query.tables.Career.CAREER;

	/**
	 * 業務経歴詳細
	 */
	public static final CareerDetail CAREER_DETAIL = jp.co.kunisys.member.query.tables.CareerDetail.CAREER_DETAIL;

	/**
	 * 業務経歴詳細スキル
	 */
	public static final CareerDetailSkill CAREER_DETAIL_SKILL = jp.co.kunisys.member.query.tables.CareerDetailSkill.CAREER_DETAIL_SKILL;

	/**
	 * 部署
	 */
	public static final Department DEPARTMENT = jp.co.kunisys.member.query.tables.Department.DEPARTMENT;

	/**
	 * 学歴
	 */
	public static final EduBackground EDU_BACKGROUND = jp.co.kunisys.member.query.tables.EduBackground.EDU_BACKGROUND;

	/**
	 * 性別
	 */
	public static final Gender GENDER = jp.co.kunisys.member.query.tables.Gender.GENDER;

	/**
	 * IPV4アドレス管理
	 */
	public static final Ipv4AddressManage IPV4_ADDRESS_MANAGE = jp.co.kunisys.member.query.tables.Ipv4AddressManage.IPV4_ADDRESS_MANAGE;

	/**
	 * アクセス権限台帳
	 */
	public static final IsmsAccessAuth ISMS_ACCESS_AUTH = jp.co.kunisys.member.query.tables.IsmsAccessAuth.ISMS_ACCESS_AUTH;

	/**
	 * アクセス権限台帳サーバパス
	 */
	public static final IsmsAccessAuthServerPath ISMS_ACCESS_AUTH_SERVER_PATH = jp.co.kunisys.member.query.tables.IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH;

	/**
	 * アクセス権限台帳対象者
	 */
	public static final IsmsAccessAuthUser ISMS_ACCESS_AUTH_USER = jp.co.kunisys.member.query.tables.IsmsAccessAuthUser.ISMS_ACCESS_AUTH_USER;

	/**
	 * 資産管理台帳
	 */
	public static final IsmsAsset ISMS_ASSET = jp.co.kunisys.member.query.tables.IsmsAsset.ISMS_ASSET;

	/**
	 * アセスメント資産
	 */
	public static final IsmsAssetAssess ISMS_ASSET_ASSESS = jp.co.kunisys.member.query.tables.IsmsAssetAssess.ISMS_ASSET_ASSESS;

	/**
	 * アセスメント管理
	 */
	public static final IsmsAssetAssessManage ISMS_ASSET_ASSESS_MANAGE = jp.co.kunisys.member.query.tables.IsmsAssetAssessManage.ISMS_ASSET_ASSESS_MANAGE;

	/**
	 * アセスメント資産対応管理策
	 */
	public static final IsmsAssetAssessManagePlan ISMS_ASSET_ASSESS_MANAGE_PLAN = jp.co.kunisys.member.query.tables.IsmsAssetAssessManagePlan.ISMS_ASSET_ASSESS_MANAGE_PLAN;

	/**
	 * アセスメント資産対応後脅威脆弱性
	 */
	public static final IsmsAssetAssessManageRisk ISMS_ASSET_ASSESS_MANAGE_RISK = jp.co.kunisys.member.query.tables.IsmsAssetAssessManageRisk.ISMS_ASSET_ASSESS_MANAGE_RISK;

	/**
	 * アセスメント資産脅威脆弱性
	 */
	public static final IsmsAssetAssessRisk ISMS_ASSET_ASSESS_RISK = jp.co.kunisys.member.query.tables.IsmsAssetAssessRisk.ISMS_ASSET_ASSESS_RISK;

	/**
	 * アセスメント資産価値
	 */
	public static final IsmsAssetAssessValue ISMS_ASSET_ASSESS_VALUE = jp.co.kunisys.member.query.tables.IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE;

	/**
	 * 資産ID履歴
	 */
	public static final IsmsAssetId ISMS_ASSET_ID = jp.co.kunisys.member.query.tables.IsmsAssetId.ISMS_ASSET_ID;

	/**
	 * 適用管理策
	 */
	public static final IsmsAssetManagePlan ISMS_ASSET_MANAGE_PLAN = jp.co.kunisys.member.query.tables.IsmsAssetManagePlan.ISMS_ASSET_MANAGE_PLAN;

	/**
	 * 資産分類表
	 */
	public static final IsmsAssetPattern ISMS_ASSET_PATTERN = jp.co.kunisys.member.query.tables.IsmsAssetPattern.ISMS_ASSET_PATTERN;

	/**
	 * 資産脅威脆弱性
	 */
	public static final IsmsAssetRisk ISMS_ASSET_RISK = jp.co.kunisys.member.query.tables.IsmsAssetRisk.ISMS_ASSET_RISK;

	/**
	 * 資産保管形態
	 */
	public static final IsmsAssetType ISMS_ASSET_TYPE = jp.co.kunisys.member.query.tables.IsmsAssetType.ISMS_ASSET_TYPE;

	/**
	 * 資産保管形態カテゴリ
	 */
	public static final IsmsAssetTypeCategory ISMS_ASSET_TYPE_CATEGORY = jp.co.kunisys.member.query.tables.IsmsAssetTypeCategory.ISMS_ASSET_TYPE_CATEGORY;

	/**
	 * 上位管理者
	 */
	public static final IsmsGreaterManager ISMS_GREATER_MANAGER = jp.co.kunisys.member.query.tables.IsmsGreaterManager.ISMS_GREATER_MANAGER;

	/**
	 * ハードウェア台帳
	 */
	public static final IsmsHardware ISMS_HARDWARE = jp.co.kunisys.member.query.tables.IsmsHardware.ISMS_HARDWARE;

	/**
	 * 管理策
	 */
	public static final IsmsManagePlan ISMS_MANAGE_PLAN = jp.co.kunisys.member.query.tables.IsmsManagePlan.ISMS_MANAGE_PLAN;

	/**
	 * 外部文書台帳
	 */
	public static final IsmsOutsideDoc ISMS_OUTSIDE_DOC = jp.co.kunisys.member.query.tables.IsmsOutsideDoc.ISMS_OUTSIDE_DOC;

	/**
	 * 保管管理簿
	 */
	public static final IsmsOutsideMedia ISMS_OUTSIDE_MEDIA = jp.co.kunisys.member.query.tables.IsmsOutsideMedia.ISMS_OUTSIDE_MEDIA;

	/**
	 * ソフトウェア台帳
	 */
	public static final IsmsSoftware ISMS_SOFTWARE = jp.co.kunisys.member.query.tables.IsmsSoftware.ISMS_SOFTWARE;

	/**
	 * ソフトウェア使用状況
	 */
	public static final IsmsSoftwareUse ISMS_SOFTWARE_USE = jp.co.kunisys.member.query.tables.IsmsSoftwareUse.ISMS_SOFTWARE_USE;

	/**
	 * 入出庫管理台帳
	 */
	public static final IsmsStore ISMS_STORE = jp.co.kunisys.member.query.tables.IsmsStore.ISMS_STORE;

	/**
	 * 入出庫管理台帳資産管理
	 */
	public static final IsmsStoreAsset ISMS_STORE_ASSET = jp.co.kunisys.member.query.tables.IsmsStoreAsset.ISMS_STORE_ASSET;

	/**
	 * 入出庫管理台帳廃棄
	 */
	public static final IsmsStoreDispose ISMS_STORE_DISPOSE = jp.co.kunisys.member.query.tables.IsmsStoreDispose.ISMS_STORE_DISPOSE;

	/**
	 * 入出庫管理台帳入庫
	 */
	public static final IsmsStoreIn ISMS_STORE_IN = jp.co.kunisys.member.query.tables.IsmsStoreIn.ISMS_STORE_IN;

	/**
	 * 入出庫管理台帳出庫
	 */
	public static final IsmsStoreOut ISMS_STORE_OUT = jp.co.kunisys.member.query.tables.IsmsStoreOut.ISMS_STORE_OUT;

	/**
	 * システム台帳
	 */
	public static final IsmsSystemInfo ISMS_SYSTEM_INFO = jp.co.kunisys.member.query.tables.IsmsSystemInfo.ISMS_SYSTEM_INFO;

	/**
	 * システム台帳関連プロジェクト
	 */
	public static final IsmsSystemProject ISMS_SYSTEM_PROJECT = jp.co.kunisys.member.query.tables.IsmsSystemProject.ISMS_SYSTEM_PROJECT;

	/**
	 * 仮想マシン台帳
	 */
	public static final IsmsVirtualMachine ISMS_VIRTUAL_MACHINE = jp.co.kunisys.member.query.tables.IsmsVirtualMachine.ISMS_VIRTUAL_MACHINE;

	/**
	 * 区分
	 */
	public static final Kubun KUBUN = jp.co.kunisys.member.query.tables.Kubun.KUBUN;

	/**
	 * 資格免許
	 */
	public static final License LICENSE = jp.co.kunisys.member.query.tables.License.LICENSE;

	/**
	 * 個人スキル
	 */
	public static final PersonalSkill PERSONAL_SKILL = jp.co.kunisys.member.query.tables.PersonalSkill.PERSONAL_SKILL;

	/**
	 * 職位
	 */
	public static final Post POST = jp.co.kunisys.member.query.tables.Post.POST;

	/**
	 * 連係用部署情報
	 */
	public static final RelateDepartment RELATE_DEPARTMENT = jp.co.kunisys.member.query.tables.RelateDepartment.RELATE_DEPARTMENT;

	/**
	 * 連係用ユーザ情報
	 */
	public static final RelateUser RELATE_USER = jp.co.kunisys.member.query.tables.RelateUser.RELATE_USER;

	/**
	 * 学校
	 */
	public static final School SCHOOL = jp.co.kunisys.member.query.tables.School.SCHOOL;

	/**
	 * スキル
	 */
	public static final Skill SKILL = jp.co.kunisys.member.query.tables.Skill.SKILL;

	/**
	 * スキル種類
	 */
	public static final SkillKind SKILL_KIND = jp.co.kunisys.member.query.tables.SkillKind.SKILL_KIND;

	/**
	 * メッセージ
	 */
	public static final TopMessage TOP_MESSAGE = jp.co.kunisys.member.query.tables.TopMessage.TOP_MESSAGE;

	/**
	 * ユーザ権限
	 */
	public static final UserAuth USER_AUTH = jp.co.kunisys.member.query.tables.UserAuth.USER_AUTH;

	/**
	 * ユーザ情報
	 */
	public static final UserInfo USER_INFO = jp.co.kunisys.member.query.tables.UserInfo.USER_INFO;

	/**
	 * 辞令情報
	 */
	public static final UserInfoAppointment USER_INFO_APPOINTMENT = jp.co.kunisys.member.query.tables.UserInfoAppointment.USER_INFO_APPOINTMENT;

	/**
	 * 家族情報
	 */
	public static final UserInfoFamily USER_INFO_FAMILY = jp.co.kunisys.member.query.tables.UserInfoFamily.USER_INFO_FAMILY;

	/**
	 * 保険情報
	 */
	public static final UserInfoInsurance USER_INFO_INSURANCE = jp.co.kunisys.member.query.tables.UserInfoInsurance.USER_INFO_INSURANCE;

	/**
	 * 退職情報
	 */
	public static final UserInfoRetire USER_INFO_RETIRE = jp.co.kunisys.member.query.tables.UserInfoRetire.USER_INFO_RETIRE;

	/**
	 * VIEW
	 */
	public static final UserInfoView USER_INFO_VIEW = jp.co.kunisys.member.query.tables.UserInfoView.USER_INFO_VIEW;

	/**
	 * ユーザ勤務先
	 */
	public static final UserInfoWorkplace USER_INFO_WORKPLACE = jp.co.kunisys.member.query.tables.UserInfoWorkplace.USER_INFO_WORKPLACE;

	/**
	 * 勤務先
	 */
	public static final Workplace WORKPLACE = jp.co.kunisys.member.query.tables.Workplace.WORKPLACE;
}
