/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.AnalysisJobInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分析処理情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisJobInfoRecord extends UpdatableRecordImpl<AnalysisJobInfoRecord> implements Record2<Integer, Timestamp> {

	private static final long serialVersionUID = -271510741;

	/**
	 * Setter for <code>members.analysis_job_info.id</code>. ID
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.analysis_job_info.id</code>. ID
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.analysis_job_info.job_date</code>. 処理実行日
	 */
	public void setJobDate(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.analysis_job_info.job_date</code>. 処理実行日
	 */
	public Timestamp getJobDate() {
		return (Timestamp) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Timestamp> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Timestamp> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AnalysisJobInfo.ANALYSIS_JOB_INFO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return AnalysisJobInfo.ANALYSIS_JOB_INFO.JOB_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getJobDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisJobInfoRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisJobInfoRecord value2(Timestamp value) {
		setJobDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisJobInfoRecord values(Integer value1, Timestamp value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnalysisJobInfoRecord
	 */
	public AnalysisJobInfoRecord() {
		super(AnalysisJobInfo.ANALYSIS_JOB_INFO);
	}

	/**
	 * Create a detached, initialised AnalysisJobInfoRecord
	 */
	public AnalysisJobInfoRecord(Integer id, Timestamp jobDate) {
		super(AnalysisJobInfo.ANALYSIS_JOB_INFO);

		setValue(0, id);
		setValue(1, jobDate);
	}
}
