/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.AnalysisBusho;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分析部署
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisBushoRecord extends UpdatableRecordImpl<AnalysisBushoRecord> implements Record2<String, String> {

	private static final long serialVersionUID = 749031745;

	/**
	 * Setter for <code>members.analysis_busho.busho_code</code>. 部署コード
	 */
	public void setBushoCode(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.analysis_busho.busho_code</code>. 部署コード
	 */
	public String getBushoCode() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>members.analysis_busho.busho_name</code>. 部署名
	 */
	public void setBushoName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.analysis_busho.busho_name</code>. 部署名
	 */
	public String getBushoName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AnalysisBusho.ANALYSIS_BUSHO.BUSHO_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AnalysisBusho.ANALYSIS_BUSHO.BUSHO_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getBushoCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getBushoName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisBushoRecord value1(String value) {
		setBushoCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisBushoRecord value2(String value) {
		setBushoName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisBushoRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnalysisBushoRecord
	 */
	public AnalysisBushoRecord() {
		super(AnalysisBusho.ANALYSIS_BUSHO);
	}

	/**
	 * Create a detached, initialised AnalysisBushoRecord
	 */
	public AnalysisBushoRecord(String bushoCode, String bushoName) {
		super(AnalysisBusho.ANALYSIS_BUSHO);

		setValue(0, bushoCode);
		setValue(1, bushoName);
	}
}
