/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.AnalysisProjectSummary;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分析プロジェクト集計
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisProjectSummaryRecord extends UpdatableRecordImpl<AnalysisProjectSummaryRecord> implements Record19<String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

	private static final long serialVersionUID = -1192293626;

	/**
	 * Setter for <code>members.analysis_project_summary.project_code</code>. プロジェクトコード
	 */
	public void setProjectCode(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.project_code</code>. プロジェクトコード
	 */
	public String getProjectCode() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.ukeoi_kingaku_with_tax</code>. 請負金額税込
	 */
	public void setUkeoiKingakuWithTax(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.ukeoi_kingaku_with_tax</code>. 請負金額税込
	 */
	public BigDecimal getUkeoiKingakuWithTax() {
		return (BigDecimal) getValue(1);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.ukeoi_kingaku</code>. 請負金額
	 */
	public void setUkeoiKingaku(BigDecimal value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.ukeoi_kingaku</code>. 請負金額
	 */
	public BigDecimal getUkeoiKingaku() {
		return (BigDecimal) getValue(2);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.yosan_shiire</code>. 予算仕入
	 */
	public void setYosanShiire(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.yosan_shiire</code>. 予算仕入
	 */
	public BigDecimal getYosanShiire() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.yosan_gaichu</code>. 予算外注
	 */
	public void setYosanGaichu(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.yosan_gaichu</code>. 予算外注
	 */
	public BigDecimal getYosanGaichu() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.yosan_dev</code>. 予算開発
	 */
	public void setYosanDev(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.yosan_dev</code>. 予算開発
	 */
	public BigDecimal getYosanDev() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.yosan_rieki</code>. 予算利益
	 */
	public void setYosanRieki(BigDecimal value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.yosan_rieki</code>. 予算利益
	 */
	public BigDecimal getYosanRieki() {
		return (BigDecimal) getValue(6);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.jisseki_uriage</code>. 実績売上
	 */
	public void setJissekiUriage(BigDecimal value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.jisseki_uriage</code>. 実績売上
	 */
	public BigDecimal getJissekiUriage() {
		return (BigDecimal) getValue(7);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.jisseki_shiire</code>. 実績原価仕入
	 */
	public void setJissekiShiire(BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.jisseki_shiire</code>. 実績原価仕入
	 */
	public BigDecimal getJissekiShiire() {
		return (BigDecimal) getValue(8);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.jisseki_roumu</code>. 実績原価労務
	 */
	public void setJissekiRoumu(BigDecimal value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.jisseki_roumu</code>. 実績原価労務
	 */
	public BigDecimal getJissekiRoumu() {
		return (BigDecimal) getValue(9);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.jisseki_gaichu</code>. 実績原価外注
	 */
	public void setJissekiGaichu(BigDecimal value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.jisseki_gaichu</code>. 実績原価外注
	 */
	public BigDecimal getJissekiGaichu() {
		return (BigDecimal) getValue(10);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.jisseki_keihi</code>. 実績原価経費
	 */
	public void setJissekiKeihi(BigDecimal value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.jisseki_keihi</code>. 実績原価経費
	 */
	public BigDecimal getJissekiKeihi() {
		return (BigDecimal) getValue(11);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.work_time</code>. 稼働時間通常
	 */
	public void setWorkTime(BigDecimal value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.work_time</code>. 稼働時間通常
	 */
	public BigDecimal getWorkTime() {
		return (BigDecimal) getValue(12);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.work_time_jikangai</code>. 稼働時間時間外
	 */
	public void setWorkTimeJikangai(BigDecimal value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.work_time_jikangai</code>. 稼働時間時間外
	 */
	public BigDecimal getWorkTimeJikangai() {
		return (BigDecimal) getValue(13);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.work_time_kyujitsu</code>. 稼働時間休日
	 */
	public void setWorkTimeKyujitsu(BigDecimal value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.work_time_kyujitsu</code>. 稼働時間休日
	 */
	public BigDecimal getWorkTimeKyujitsu() {
		return (BigDecimal) getValue(14);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.work_time_houteigai</code>. 稼働時間法定外
	 */
	public void setWorkTimeHouteigai(BigDecimal value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.work_time_houteigai</code>. 稼働時間法定外
	 */
	public BigDecimal getWorkTimeHouteigai() {
		return (BigDecimal) getValue(15);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.work_time_sinya</code>. 稼働時間深夜
	 */
	public void setWorkTimeSinya(BigDecimal value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.work_time_sinya</code>. 稼働時間深夜
	 */
	public BigDecimal getWorkTimeSinya() {
		return (BigDecimal) getValue(16);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.work_time_houteigai_sinya</code>. 稼働時間法定外深夜
	 */
	public void setWorkTimeHouteigaiSinya(BigDecimal value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.work_time_houteigai_sinya</code>. 稼働時間法定外深夜
	 */
	public BigDecimal getWorkTimeHouteigaiSinya() {
		return (BigDecimal) getValue(17);
	}

	/**
	 * Setter for <code>members.analysis_project_summary.record_time</code>. 稼働時間記録
	 */
	public void setRecordTime(BigDecimal value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>members.analysis_project_summary.record_time</code>. 稼働時間記録
	 */
	public BigDecimal getRecordTime() {
		return (BigDecimal) getValue(18);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record19 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
		return (Row19) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row19<String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
		return (Row19) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.PROJECT_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.UKEOI_KINGAKU_WITH_TAX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field3() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.UKEOI_KINGAKU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.YOSAN_SHIIRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.YOSAN_GAICHU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.YOSAN_DEV;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field7() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.YOSAN_RIEKI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field8() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.JISSEKI_URIAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field9() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.JISSEKI_SHIIRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field10() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.JISSEKI_ROUMU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field11() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.JISSEKI_GAICHU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field12() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.JISSEKI_KEIHI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field13() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.WORK_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field14() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.WORK_TIME_JIKANGAI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field15() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.WORK_TIME_KYUJITSU;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field16() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.WORK_TIME_HOUTEIGAI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field17() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.WORK_TIME_SINYA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field18() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.WORK_TIME_HOUTEIGAI_SINYA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field19() {
		return AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY.RECORD_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getProjectCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getUkeoiKingakuWithTax();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value3() {
		return getUkeoiKingaku();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getYosanShiire();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getYosanGaichu();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getYosanDev();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value7() {
		return getYosanRieki();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value8() {
		return getJissekiUriage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value9() {
		return getJissekiShiire();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value10() {
		return getJissekiRoumu();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value11() {
		return getJissekiGaichu();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value12() {
		return getJissekiKeihi();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value13() {
		return getWorkTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value14() {
		return getWorkTimeJikangai();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value15() {
		return getWorkTimeKyujitsu();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value16() {
		return getWorkTimeHouteigai();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value17() {
		return getWorkTimeSinya();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value18() {
		return getWorkTimeHouteigaiSinya();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value19() {
		return getRecordTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value1(String value) {
		setProjectCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value2(BigDecimal value) {
		setUkeoiKingakuWithTax(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value3(BigDecimal value) {
		setUkeoiKingaku(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value4(BigDecimal value) {
		setYosanShiire(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value5(BigDecimal value) {
		setYosanGaichu(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value6(BigDecimal value) {
		setYosanDev(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value7(BigDecimal value) {
		setYosanRieki(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value8(BigDecimal value) {
		setJissekiUriage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value9(BigDecimal value) {
		setJissekiShiire(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value10(BigDecimal value) {
		setJissekiRoumu(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value11(BigDecimal value) {
		setJissekiGaichu(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value12(BigDecimal value) {
		setJissekiKeihi(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value13(BigDecimal value) {
		setWorkTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value14(BigDecimal value) {
		setWorkTimeJikangai(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value15(BigDecimal value) {
		setWorkTimeKyujitsu(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value16(BigDecimal value) {
		setWorkTimeHouteigai(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value17(BigDecimal value) {
		setWorkTimeSinya(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value18(BigDecimal value) {
		setWorkTimeHouteigaiSinya(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord value19(BigDecimal value) {
		setRecordTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummaryRecord values(String value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, BigDecimal value14, BigDecimal value15, BigDecimal value16, BigDecimal value17, BigDecimal value18, BigDecimal value19) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		value18(value18);
		value19(value19);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnalysisProjectSummaryRecord
	 */
	public AnalysisProjectSummaryRecord() {
		super(AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY);
	}

	/**
	 * Create a detached, initialised AnalysisProjectSummaryRecord
	 */
	public AnalysisProjectSummaryRecord(String projectCode, BigDecimal ukeoiKingakuWithTax, BigDecimal ukeoiKingaku, BigDecimal yosanShiire, BigDecimal yosanGaichu, BigDecimal yosanDev, BigDecimal yosanRieki, BigDecimal jissekiUriage, BigDecimal jissekiShiire, BigDecimal jissekiRoumu, BigDecimal jissekiGaichu, BigDecimal jissekiKeihi, BigDecimal workTime, BigDecimal workTimeJikangai, BigDecimal workTimeKyujitsu, BigDecimal workTimeHouteigai, BigDecimal workTimeSinya, BigDecimal workTimeHouteigaiSinya, BigDecimal recordTime) {
		super(AnalysisProjectSummary.ANALYSIS_PROJECT_SUMMARY);

		setValue(0, projectCode);
		setValue(1, ukeoiKingakuWithTax);
		setValue(2, ukeoiKingaku);
		setValue(3, yosanShiire);
		setValue(4, yosanGaichu);
		setValue(5, yosanDev);
		setValue(6, yosanRieki);
		setValue(7, jissekiUriage);
		setValue(8, jissekiShiire);
		setValue(9, jissekiRoumu);
		setValue(10, jissekiGaichu);
		setValue(11, jissekiKeihi);
		setValue(12, workTime);
		setValue(13, workTimeJikangai);
		setValue(14, workTimeKyujitsu);
		setValue(15, workTimeHouteigai);
		setValue(16, workTimeSinya);
		setValue(17, workTimeHouteigaiSinya);
		setValue(18, recordTime);
	}
}
