/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.AnalysisProjectInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 分析プロジェクト情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisProjectInfoRecord extends UpdatableRecordImpl<AnalysisProjectInfoRecord> implements Record9<String, String, String, BigDecimal, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 1215339502;

	/**
	 * Setter for <code>members.analysis_project_info.project_code</code>. プロジェクトコード
	 */
	public void setProjectCode(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.project_code</code>. プロジェクトコード
	 */
	public String getProjectCode() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>members.analysis_project_info.project_type</code>. プロジェクト形態
	 */
	public void setProjectType(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.project_type</code>. プロジェクト形態
	 */
	public String getProjectType() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.analysis_project_info.description</code>. プロジェクト概要
	 */
	public void setDescription(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.description</code>. プロジェクト概要
	 */
	public String getDescription() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.analysis_project_info.plan_man_hour_total</code>. 予定総工数
	 */
	public void setPlanManHourTotal(BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.plan_man_hour_total</code>. 予定総工数
	 */
	public BigDecimal getPlanManHourTotal() {
		return (BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>members.analysis_project_info.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>members.analysis_project_info.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>members.analysis_project_info.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>members.analysis_project_info.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>members.analysis_project_info.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.analysis_project_info.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, BigDecimal, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<String, String, String, BigDecimal, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.PROJECT_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.PROJECT_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field4() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.PLAN_MAN_HOUR_TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return AnalysisProjectInfo.ANALYSIS_PROJECT_INFO.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getProjectCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getProjectType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value4() {
		return getPlanManHourTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value1(String value) {
		setProjectCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value2(String value) {
		setProjectType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value3(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value4(BigDecimal value) {
		setPlanManHourTotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value5(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value6(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value7(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value8(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord value9(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectInfoRecord values(String value1, String value2, String value3, BigDecimal value4, Timestamp value5, Integer value6, Timestamp value7, Integer value8, Integer value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AnalysisProjectInfoRecord
	 */
	public AnalysisProjectInfoRecord() {
		super(AnalysisProjectInfo.ANALYSIS_PROJECT_INFO);
	}

	/**
	 * Create a detached, initialised AnalysisProjectInfoRecord
	 */
	public AnalysisProjectInfoRecord(String projectCode, String projectType, String description, BigDecimal planManHourTotal, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Integer version) {
		super(AnalysisProjectInfo.ANALYSIS_PROJECT_INFO);

		setValue(0, projectCode);
		setValue(1, projectType);
		setValue(2, description);
		setValue(3, planManHourTotal);
		setValue(4, created);
		setValue(5, createdUser);
		setValue(6, updated);
		setValue(7, updatedUser);
		setValue(8, version);
	}
}
