/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.CareerDetailSkill;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record4;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 業務経歴詳細スキル
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CareerDetailSkillRecord extends UpdatableRecordImpl<CareerDetailSkillRecord> implements Record13<Integer, Integer, Integer, Integer, Integer, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = -610210794;

	/**
	 * Setter for <code>members.career_detail_skill.user_id</code>. ユーザID
	 */
	public void setUserId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.user_id</code>. ユーザID
	 */
	public Integer getUserId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.career_detail_skill.job_no</code>. 業務経歴番号
	 */
	public void setJobNo(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.job_no</code>. 業務経歴番号
	 */
	public Integer getJobNo() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.career_detail_skill.skill_type_no</code>. スキル種類番号
	 */
	public void setSkillTypeNo(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.skill_type_no</code>. スキル種類番号
	 */
	public Integer getSkillTypeNo() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>members.career_detail_skill.no</code>. 連番
	 */
	public void setNo(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.no</code>. 連番
	 */
	public Integer getNo() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>members.career_detail_skill.skill_no</code>. スキル番号
	 */
	public void setSkillNo(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.skill_no</code>. スキル番号
	 */
	public Integer getSkillNo() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>members.career_detail_skill.comment</code>. コメント
	 */
	public void setComment(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.comment</code>. コメント
	 */
	public String getComment() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>members.career_detail_skill.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>members.career_detail_skill.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>members.career_detail_skill.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>members.career_detail_skill.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>members.career_detail_skill.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>members.career_detail_skill.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>members.career_detail_skill.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>members.career_detail_skill.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record4<Integer, Integer, Integer, Integer> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, Integer, Integer, Integer, Integer, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row13<Integer, Integer, Integer, Integer, Integer, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.JOB_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.SKILL_TYPE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.SKILL_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return CareerDetailSkill.CAREER_DETAIL_SKILL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getJobNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSkillTypeNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getSkillNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value1(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value2(Integer value) {
		setJobNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value3(Integer value) {
		setSkillTypeNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value4(Integer value) {
		setNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value5(Integer value) {
		setSkillNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value6(String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value7(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value8(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value9(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value10(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value11(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value12(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord value13(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkillRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, Timestamp value7, Integer value8, Timestamp value9, Integer value10, Timestamp value11, Integer value12, Integer value13) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CareerDetailSkillRecord
	 */
	public CareerDetailSkillRecord() {
		super(CareerDetailSkill.CAREER_DETAIL_SKILL);
	}

	/**
	 * Create a detached, initialised CareerDetailSkillRecord
	 */
	public CareerDetailSkillRecord(Integer userId, Integer jobNo, Integer skillTypeNo, Integer no, Integer skillNo, String comment, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(CareerDetailSkill.CAREER_DETAIL_SKILL);

		setValue(0, userId);
		setValue(1, jobNo);
		setValue(2, skillTypeNo);
		setValue(3, no);
		setValue(4, skillNo);
		setValue(5, comment);
		setValue(6, created);
		setValue(7, createdUser);
		setValue(8, updated);
		setValue(9, updatedUser);
		setValue(10, deleted);
		setValue(11, deletedUser);
		setValue(12, version);
	}
}
