/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.EduBackground;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record2;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学歴
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EduBackgroundRecord extends UpdatableRecordImpl<EduBackgroundRecord> implements Record15<Integer, Integer, Integer, String, String, Integer, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = -1119065252;

	/**
	 * Setter for <code>members.edu_background.user_id</code>. ユーザID
	 */
	public void setUserId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.edu_background.user_id</code>. ユーザID
	 */
	public Integer getUserId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.edu_background.no</code>. 連番
	 */
	public void setNo(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.edu_background.no</code>. 連番
	 */
	public Integer getNo() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.edu_background.school_id</code>. 学校コード
	 */
	public void setSchoolId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.edu_background.school_id</code>. 学校コード
	 */
	public Integer getSchoolId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>members.edu_background.entrance</code>. 入学年月
	 */
	public void setEntrance(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.edu_background.entrance</code>. 入学年月
	 */
	public String getEntrance() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>members.edu_background.graduate</code>. 卒業年月
	 */
	public void setGraduate(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.edu_background.graduate</code>. 卒業年月
	 */
	public String getGraduate() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>members.edu_background.drop_out_flg</code>. 中退フラグ
	 */
	public void setDropOutFlg(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.edu_background.drop_out_flg</code>. 中退フラグ
	 */
	public Integer getDropOutFlg() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>members.edu_background.description</code>. 内容
	 */
	public void setDescription(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.edu_background.description</code>. 内容
	 */
	public String getDescription() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>members.edu_background.comment</code>. コメント
	 */
	public void setComment(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.edu_background.comment</code>. コメント
	 */
	public String getComment() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>members.edu_background.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.edu_background.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>members.edu_background.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.edu_background.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>members.edu_background.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.edu_background.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>members.edu_background.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.edu_background.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>members.edu_background.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>members.edu_background.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>members.edu_background.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>members.edu_background.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(13);
	}

	/**
	 * Setter for <code>members.edu_background.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>members.edu_background.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<Integer, Integer, Integer, String, String, Integer, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<Integer, Integer, Integer, String, String, Integer, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return EduBackground.EDU_BACKGROUND.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return EduBackground.EDU_BACKGROUND.NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return EduBackground.EDU_BACKGROUND.SCHOOL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return EduBackground.EDU_BACKGROUND.ENTRANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EduBackground.EDU_BACKGROUND.GRADUATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return EduBackground.EDU_BACKGROUND.DROP_OUT_FLG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return EduBackground.EDU_BACKGROUND.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return EduBackground.EDU_BACKGROUND.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return EduBackground.EDU_BACKGROUND.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return EduBackground.EDU_BACKGROUND.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return EduBackground.EDU_BACKGROUND.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return EduBackground.EDU_BACKGROUND.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field13() {
		return EduBackground.EDU_BACKGROUND.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field14() {
		return EduBackground.EDU_BACKGROUND.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return EduBackground.EDU_BACKGROUND.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSchoolId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getEntrance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getGraduate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getDropOutFlg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value13() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value14() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value1(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value2(Integer value) {
		setNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value3(Integer value) {
		setSchoolId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value4(String value) {
		setEntrance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value5(String value) {
		setGraduate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value6(Integer value) {
		setDropOutFlg(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value7(String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value8(String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value9(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value10(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value11(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value12(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value13(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value14(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord value15(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EduBackgroundRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, String value7, String value8, Timestamp value9, Integer value10, Timestamp value11, Integer value12, Timestamp value13, Integer value14, Integer value15) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EduBackgroundRecord
	 */
	public EduBackgroundRecord() {
		super(EduBackground.EDU_BACKGROUND);
	}

	/**
	 * Create a detached, initialised EduBackgroundRecord
	 */
	public EduBackgroundRecord(Integer userId, Integer no, Integer schoolId, String entrance, String graduate, Integer dropOutFlg, String description, String comment, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(EduBackground.EDU_BACKGROUND);

		setValue(0, userId);
		setValue(1, no);
		setValue(2, schoolId);
		setValue(3, entrance);
		setValue(4, graduate);
		setValue(5, dropOutFlg);
		setValue(6, description);
		setValue(7, comment);
		setValue(8, created);
		setValue(9, createdUser);
		setValue(10, updated);
		setValue(11, updatedUser);
		setValue(12, deleted);
		setValue(13, deletedUser);
		setValue(14, version);
	}
}
