/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsAccessAuthServerPath;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * アクセス権限台帳サーバパス
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAccessAuthServerPathRecord extends UpdatableRecordImpl<IsmsAccessAuthServerPathRecord> implements Record16<Integer, String, String, Integer, Integer, Integer, Timestamp, Integer, Long, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 718631760;

	/**
	 * Setter for <code>members.isms_access_auth_server_path.folder_id</code>. フォルダID
	 */
	public void setFolderId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.folder_id</code>. フォルダID
	 */
	public Integer getFolderId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.folder_name</code>. フォルダ名称
	 */
	public void setFolderName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.folder_name</code>. フォルダ名称
	 */
	public String getFolderName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.level</code>. フォルダ階層
	 */
	public void setLevel(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.level</code>. フォルダ階層
	 */
	public String getLevel() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.sortkey</code>. 並び順
	 */
	public void setSortkey(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.sortkey</code>. 並び順
	 */
	public Integer getSortkey() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.manager_id</code>. 管理者ID
	 */
	public void setManagerId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.manager_id</code>. 管理者ID
	 */
	public Integer getManagerId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.worker_id</code>. 作業者ID
	 */
	public void setWorkerId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.worker_id</code>. 作業者ID
	 */
	public Integer getWorkerId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.auth_set_date</code>. 設定日
	 */
	public void setAuthSetDate(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.auth_set_date</code>. 設定日
	 */
	public Timestamp getAuthSetDate() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.sheet_divide</code>. シート分け
	 */
	public void setSheetDivide(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.sheet_divide</code>. シート分け
	 */
	public Integer getSheetDivide() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.asset_id</code>. 資産ID
	 */
	public void setAssetId(Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.asset_id</code>. 資産ID
	 */
	public Long getAssetId() {
		return (Long) getValue(8);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(12);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>members.isms_access_auth_server_path.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>members.isms_access_auth_server_path.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, String, String, Integer, Integer, Integer, Timestamp, Integer, Long, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row16<Integer, String, String, Integer, Integer, Integer, Timestamp, Integer, Long, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.FOLDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.FOLDER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.SORTKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.MANAGER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.WORKER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.AUTH_SET_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.SHEET_DIVIDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field9() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field12() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field14() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getFolderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFolderName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getSortkey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getManagerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getWorkerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getAuthSetDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getSheetDivide();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value9() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value12() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value14() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value1(Integer value) {
		setFolderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value2(String value) {
		setFolderName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value3(String value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value4(Integer value) {
		setSortkey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value5(Integer value) {
		setManagerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value6(Integer value) {
		setWorkerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value7(Timestamp value) {
		setAuthSetDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value8(Integer value) {
		setSheetDivide(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value9(Long value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value10(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value11(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value12(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value13(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value14(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value15(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord value16(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAccessAuthServerPathRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Timestamp value7, Integer value8, Long value9, Timestamp value10, Integer value11, Timestamp value12, Integer value13, Timestamp value14, Integer value15, Integer value16) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsAccessAuthServerPathRecord
	 */
	public IsmsAccessAuthServerPathRecord() {
		super(IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH);
	}

	/**
	 * Create a detached, initialised IsmsAccessAuthServerPathRecord
	 */
	public IsmsAccessAuthServerPathRecord(Integer folderId, String folderName, String level, Integer sortkey, Integer managerId, Integer workerId, Timestamp authSetDate, Integer sheetDivide, Long assetId, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(IsmsAccessAuthServerPath.ISMS_ACCESS_AUTH_SERVER_PATH);

		setValue(0, folderId);
		setValue(1, folderName);
		setValue(2, level);
		setValue(3, sortkey);
		setValue(4, managerId);
		setValue(5, workerId);
		setValue(6, authSetDate);
		setValue(7, sheetDivide);
		setValue(8, assetId);
		setValue(9, created);
		setValue(10, createdUser);
		setValue(11, updated);
		setValue(12, updatedUser);
		setValue(13, deleted);
		setValue(14, deletedUser);
		setValue(15, version);
	}
}
