/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsOutsideDoc;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 外部文書台帳
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsOutsideDocRecord extends UpdatableRecordImpl<IsmsOutsideDocRecord> implements Record3<Long, Integer, String> {

	private static final long serialVersionUID = 533833386;

	/**
	 * Setter for <code>members.isms_outside_doc.asset_id</code>. 資産ID
	 */
	public void setAssetId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_outside_doc.asset_id</code>. 資産ID
	 */
	public Long getAssetId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_outside_doc.outside_doc_id</code>. 外部文書ID
	 */
	public void setOutsideDocId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_outside_doc.outside_doc_id</code>. 外部文書ID
	 */
	public Integer getOutsideDocId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.isms_outside_doc.outside_doc_no</code>. 外部文書番号
	 */
	public void setOutsideDocNo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.isms_outside_doc.outside_doc_no</code>. 外部文書番号
	 */
	public String getOutsideDocNo() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return IsmsOutsideDoc.ISMS_OUTSIDE_DOC.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return IsmsOutsideDoc.ISMS_OUTSIDE_DOC.OUTSIDE_DOC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return IsmsOutsideDoc.ISMS_OUTSIDE_DOC.OUTSIDE_DOC_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getOutsideDocId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getOutsideDocNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideDocRecord value1(Long value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideDocRecord value2(Integer value) {
		setOutsideDocId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideDocRecord value3(String value) {
		setOutsideDocNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideDocRecord values(Long value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsOutsideDocRecord
	 */
	public IsmsOutsideDocRecord() {
		super(IsmsOutsideDoc.ISMS_OUTSIDE_DOC);
	}

	/**
	 * Create a detached, initialised IsmsOutsideDocRecord
	 */
	public IsmsOutsideDocRecord(Long assetId, Integer outsideDocId, String outsideDocNo) {
		super(IsmsOutsideDoc.ISMS_OUTSIDE_DOC);

		setValue(0, assetId);
		setValue(1, outsideDocId);
		setValue(2, outsideDocNo);
	}
}
