/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsAssetAssessValue;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * アセスメント資産価値
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAssetAssessValueRecord extends UpdatableRecordImpl<IsmsAssetAssessValueRecord> implements Record7<Timestamp, Long, Integer, Integer, Integer, Integer, String> {

	private static final long serialVersionUID = -1129103547;

	/**
	 * Setter for <code>members.isms_asset_assess_value.limit_date</code>. 締切日
	 */
	public void setLimitDate(Timestamp value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.limit_date</code>. 締切日
	 */
	public Timestamp getLimitDate() {
		return (Timestamp) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_asset_assess_value.asset_id</code>. 資産ID
	 */
	public void setAssetId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.asset_id</code>. 資産ID
	 */
	public Long getAssetId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>members.isms_asset_assess_value.confidential</code>. 機密性
	 */
	public void setConfidential(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.confidential</code>. 機密性
	 */
	public Integer getConfidential() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>members.isms_asset_assess_value.integrity</code>. 完全性
	 */
	public void setIntegrity(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.integrity</code>. 完全性
	 */
	public Integer getIntegrity() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>members.isms_asset_assess_value.availability</code>. 可用性
	 */
	public void setAvailability(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.availability</code>. 可用性
	 */
	public Integer getAvailability() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>members.isms_asset_assess_value.judge</code>. 受容可否
	 */
	public void setJudge(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.judge</code>. 受容可否
	 */
	public Integer getJudge() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>members.isms_asset_assess_value.remark</code>. 備考
	 */
	public void setRemark(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.isms_asset_assess_value.remark</code>. 備考
	 */
	public String getRemark() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Timestamp, Long> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Timestamp, Long, Integer, Integer, Integer, Integer, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Timestamp, Long, Integer, Integer, Integer, Integer, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field1() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.LIMIT_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.CONFIDENTIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.INTEGRITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.AVAILABILITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.JUDGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE.REMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value1() {
		return getLimitDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getConfidential();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getIntegrity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAvailability();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getJudge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getRemark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value1(Timestamp value) {
		setLimitDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value2(Long value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value3(Integer value) {
		setConfidential(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value4(Integer value) {
		setIntegrity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value5(Integer value) {
		setAvailability(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value6(Integer value) {
		setJudge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord value7(String value) {
		setRemark(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessValueRecord values(Timestamp value1, Long value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsAssetAssessValueRecord
	 */
	public IsmsAssetAssessValueRecord() {
		super(IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE);
	}

	/**
	 * Create a detached, initialised IsmsAssetAssessValueRecord
	 */
	public IsmsAssetAssessValueRecord(Timestamp limitDate, Long assetId, Integer confidential, Integer integrity, Integer availability, Integer judge, String remark) {
		super(IsmsAssetAssessValue.ISMS_ASSET_ASSESS_VALUE);

		setValue(0, limitDate);
		setValue(1, assetId);
		setValue(2, confidential);
		setValue(3, integrity);
		setValue(4, availability);
		setValue(5, judge);
		setValue(6, remark);
	}
}
