/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsAsset;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 資産管理台帳
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAssetRecord extends UpdatableRecordImpl<IsmsAssetRecord> implements Record12<Long, Integer, String, String, Integer, String, String, String, String, Integer, Integer, String> {

	private static final long serialVersionUID = -1943198640;

	/**
	 * Setter for <code>members.isms_asset.asset_id</code>. 資産ID
	 */
	public void setAssetId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_asset.asset_id</code>. 資産ID
	 */
	public Long getAssetId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_asset.pattern_id</code>. 分類ID
	 */
	public void setPatternId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_asset.pattern_id</code>. 分類ID
	 */
	public Integer getPatternId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.isms_asset.asset_manage_no</code>. 資産管理番号
	 */
	public void setAssetManageNo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.isms_asset.asset_manage_no</code>. 資産管理番号
	 */
	public String getAssetManageNo() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.isms_asset.asset_name</code>. 資産名
	 */
	public void setAssetName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.isms_asset.asset_name</code>. 資産名
	 */
	public String getAssetName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>members.isms_asset.asset_type_id</code>. 保管形態ID
	 */
	public void setAssetTypeId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.isms_asset.asset_type_id</code>. 保管形態ID
	 */
	public Integer getAssetTypeId() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>members.isms_asset.place</code>. 保管場所
	 */
	public void setPlace(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.isms_asset.place</code>. 保管場所
	 */
	public String getPlace() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>members.isms_asset.span</code>. 保管期間
	 */
	public void setSpan(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.isms_asset.span</code>. 保管期間
	 */
	public String getSpan() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>members.isms_asset.destruction_method</code>. 破棄方法
	 */
	public void setDestructionMethod(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.isms_asset.destruction_method</code>. 破棄方法
	 */
	public String getDestructionMethod() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>members.isms_asset.section</code>. 部門
	 */
	public void setSection(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.isms_asset.section</code>. 部門
	 */
	public String getSection() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>members.isms_asset.manager_id</code>. 管理者
	 */
	public void setManagerId(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.isms_asset.manager_id</code>. 管理者
	 */
	public Integer getManagerId() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>members.isms_asset.greater_manager_id</code>. 上位管理者
	 */
	public void setGreaterManagerId(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.isms_asset.greater_manager_id</code>. 上位管理者
	 */
	public Integer getGreaterManagerId() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>members.isms_asset.remark</code>. 備考
	 */
	public void setRemark(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.isms_asset.remark</code>. 備考
	 */
	public String getRemark() {
		return (String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Long, Integer, String, String, Integer, String, String, String, String, Integer, Integer, String> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Long, Integer, String, String, Integer, String, String, String, String, Integer, Integer, String> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return IsmsAsset.ISMS_ASSET.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return IsmsAsset.ISMS_ASSET.PATTERN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return IsmsAsset.ISMS_ASSET.ASSET_MANAGE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return IsmsAsset.ISMS_ASSET.ASSET_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return IsmsAsset.ISMS_ASSET.ASSET_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return IsmsAsset.ISMS_ASSET.PLACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return IsmsAsset.ISMS_ASSET.SPAN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return IsmsAsset.ISMS_ASSET.DESTRUCTION_METHOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return IsmsAsset.ISMS_ASSET.SECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return IsmsAsset.ISMS_ASSET.MANAGER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return IsmsAsset.ISMS_ASSET.GREATER_MANAGER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return IsmsAsset.ISMS_ASSET.REMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPatternId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAssetManageNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAssetName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAssetTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getPlace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSpan();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getDestructionMethod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getSection();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getManagerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getGreaterManagerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getRemark();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value1(Long value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value2(Integer value) {
		setPatternId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value3(String value) {
		setAssetManageNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value4(String value) {
		setAssetName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value5(Integer value) {
		setAssetTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value6(String value) {
		setPlace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value7(String value) {
		setSpan(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value8(String value) {
		setDestructionMethod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value9(String value) {
		setSection(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value10(Integer value) {
		setManagerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value11(Integer value) {
		setGreaterManagerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord value12(String value) {
		setRemark(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetRecord values(Long value1, Integer value2, String value3, String value4, Integer value5, String value6, String value7, String value8, String value9, Integer value10, Integer value11, String value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsAssetRecord
	 */
	public IsmsAssetRecord() {
		super(IsmsAsset.ISMS_ASSET);
	}

	/**
	 * Create a detached, initialised IsmsAssetRecord
	 */
	public IsmsAssetRecord(Long assetId, Integer patternId, String assetManageNo, String assetName, Integer assetTypeId, String place, String span, String destructionMethod, String section, Integer managerId, Integer greaterManagerId, String remark) {
		super(IsmsAsset.ISMS_ASSET);

		setValue(0, assetId);
		setValue(1, patternId);
		setValue(2, assetManageNo);
		setValue(3, assetName);
		setValue(4, assetTypeId);
		setValue(5, place);
		setValue(6, span);
		setValue(7, destructionMethod);
		setValue(8, section);
		setValue(9, managerId);
		setValue(10, greaterManagerId);
		setValue(11, remark);
	}
}
