/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsAssetTypeCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 資産保管形態カテゴリ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAssetTypeCategoryRecord extends UpdatableRecordImpl<IsmsAssetTypeCategoryRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 1553346384;

	/**
	 * Setter for <code>members.isms_asset_type_category.asset_type_category_id</code>. 保管形態カテゴリID
	 */
	public void setAssetTypeCategoryId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_asset_type_category.asset_type_category_id</code>. 保管形態カテゴリID
	 */
	public Integer getAssetTypeCategoryId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_asset_type_category.name</code>. 保管形態カテゴリ名称
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_asset_type_category.name</code>. 保管形態カテゴリ名称
	 */
	public String getName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return IsmsAssetTypeCategory.ISMS_ASSET_TYPE_CATEGORY.ASSET_TYPE_CATEGORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return IsmsAssetTypeCategory.ISMS_ASSET_TYPE_CATEGORY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getAssetTypeCategoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetTypeCategoryRecord value1(Integer value) {
		setAssetTypeCategoryId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetTypeCategoryRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetTypeCategoryRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsAssetTypeCategoryRecord
	 */
	public IsmsAssetTypeCategoryRecord() {
		super(IsmsAssetTypeCategory.ISMS_ASSET_TYPE_CATEGORY);
	}

	/**
	 * Create a detached, initialised IsmsAssetTypeCategoryRecord
	 */
	public IsmsAssetTypeCategoryRecord(Integer assetTypeCategoryId, String name) {
		super(IsmsAssetTypeCategory.ISMS_ASSET_TYPE_CATEGORY);

		setValue(0, assetTypeCategoryId);
		setValue(1, name);
	}
}
