/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsOutsideMedia;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 保管管理簿
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsOutsideMediaRecord extends UpdatableRecordImpl<IsmsOutsideMediaRecord> implements Record3<Long, Integer, String> {

	private static final long serialVersionUID = 2085665144;

	/**
	 * Setter for <code>members.isms_outside_media.asset_id</code>. 資産ID
	 */
	public void setAssetId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_outside_media.asset_id</code>. 資産ID
	 */
	public Long getAssetId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_outside_media.outside_media_id</code>. 保管管理簿ID
	 */
	public void setOutsideMediaId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_outside_media.outside_media_id</code>. 保管管理簿ID
	 */
	public Integer getOutsideMediaId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.isms_outside_media.outside_media_no</code>. 保管管理簿番号
	 */
	public void setOutsideMediaNo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.isms_outside_media.outside_media_no</code>. 保管管理簿番号
	 */
	public String getOutsideMediaNo() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Long, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return IsmsOutsideMedia.ISMS_OUTSIDE_MEDIA.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return IsmsOutsideMedia.ISMS_OUTSIDE_MEDIA.OUTSIDE_MEDIA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return IsmsOutsideMedia.ISMS_OUTSIDE_MEDIA.OUTSIDE_MEDIA_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getOutsideMediaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getOutsideMediaNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideMediaRecord value1(Long value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideMediaRecord value2(Integer value) {
		setOutsideMediaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideMediaRecord value3(String value) {
		setOutsideMediaNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideMediaRecord values(Long value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsOutsideMediaRecord
	 */
	public IsmsOutsideMediaRecord() {
		super(IsmsOutsideMedia.ISMS_OUTSIDE_MEDIA);
	}

	/**
	 * Create a detached, initialised IsmsOutsideMediaRecord
	 */
	public IsmsOutsideMediaRecord(Long assetId, Integer outsideMediaId, String outsideMediaNo) {
		super(IsmsOutsideMedia.ISMS_OUTSIDE_MEDIA);

		setValue(0, assetId);
		setValue(1, outsideMediaId);
		setValue(2, outsideMediaNo);
	}
}
