/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.IsmsAssetId;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 資産ID履歴
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAssetIdRecord extends UpdatableRecordImpl<IsmsAssetIdRecord> implements Record8<Long, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 1534541791;

	/**
	 * Setter for <code>members.isms_asset_id.asset_id</code>. 資産ID
	 */
	public void setAssetId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.asset_id</code>. 資産ID
	 */
	public Long getAssetId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>members.isms_asset_id.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>members.isms_asset_id.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>members.isms_asset_id.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>members.isms_asset_id.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>members.isms_asset_id.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>members.isms_asset_id.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>members.isms_asset_id.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.isms_asset_id.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Long, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return IsmsAssetId.ISMS_ASSET_ID.ASSET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return IsmsAssetId.ISMS_ASSET_ID.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return IsmsAssetId.ISMS_ASSET_ID.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return IsmsAssetId.ISMS_ASSET_ID.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return IsmsAssetId.ISMS_ASSET_ID.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return IsmsAssetId.ISMS_ASSET_ID.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return IsmsAssetId.ISMS_ASSET_ID.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return IsmsAssetId.ISMS_ASSET_ID.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getAssetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value1(Long value) {
		setAssetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value2(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value3(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value4(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value5(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value6(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value7(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord value8(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetIdRecord values(Long value1, Timestamp value2, Integer value3, Timestamp value4, Integer value5, Timestamp value6, Integer value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IsmsAssetIdRecord
	 */
	public IsmsAssetIdRecord() {
		super(IsmsAssetId.ISMS_ASSET_ID);
	}

	/**
	 * Create a detached, initialised IsmsAssetIdRecord
	 */
	public IsmsAssetIdRecord(Long assetId, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(IsmsAssetId.ISMS_ASSET_ID);

		setValue(0, assetId);
		setValue(1, created);
		setValue(2, createdUser);
		setValue(3, updated);
		setValue(4, updatedUser);
		setValue(5, deleted);
		setValue(6, deletedUser);
		setValue(7, version);
	}
}
