/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.Kubun;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 区分
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KubunRecord extends UpdatableRecordImpl<KubunRecord> implements Record12<Integer, String, String, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 1654057410;

	/**
	 * Setter for <code>members.kubun.seq</code>. 区分番号
	 */
	public void setSeq(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.kubun.seq</code>. 区分番号
	 */
	public Integer getSeq() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.kubun.type_code</code>. 区分種別コード
	 */
	public void setTypeCode(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.kubun.type_code</code>. 区分種別コード
	 */
	public String getTypeCode() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.kubun.type_name</code>. 区分種別名
	 */
	public void setTypeName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.kubun.type_name</code>. 区分種別名
	 */
	public String getTypeName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.kubun.code</code>. 区分コード
	 */
	public void setCode(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.kubun.code</code>. 区分コード
	 */
	public String getCode() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>members.kubun.name</code>. 区分名
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.kubun.name</code>. 区分名
	 */
	public String getName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>members.kubun.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.kubun.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>members.kubun.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.kubun.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>members.kubun.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.kubun.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>members.kubun.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.kubun.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>members.kubun.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.kubun.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>members.kubun.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.kubun.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>members.kubun.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.kubun.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, String, String, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, String, String, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Kubun.KUBUN.SEQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Kubun.KUBUN.TYPE_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Kubun.KUBUN.TYPE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Kubun.KUBUN.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Kubun.KUBUN.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Kubun.KUBUN.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Kubun.KUBUN.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return Kubun.KUBUN.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Kubun.KUBUN.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return Kubun.KUBUN.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return Kubun.KUBUN.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Kubun.KUBUN.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getSeq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getTypeCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTypeName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value1(Integer value) {
		setSeq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value2(String value) {
		setTypeCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value3(String value) {
		setTypeName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value4(String value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value6(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value7(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value8(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value9(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value10(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value11(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord value12(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KubunRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Integer value7, Timestamp value8, Integer value9, Timestamp value10, Integer value11, Integer value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KubunRecord
	 */
	public KubunRecord() {
		super(Kubun.KUBUN);
	}

	/**
	 * Create a detached, initialised KubunRecord
	 */
	public KubunRecord(Integer seq, String typeCode, String typeName, String code, String name, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(Kubun.KUBUN);

		setValue(0, seq);
		setValue(1, typeCode);
		setValue(2, typeName);
		setValue(3, code);
		setValue(4, name);
		setValue(5, created);
		setValue(6, createdUser);
		setValue(7, updated);
		setValue(8, updatedUser);
		setValue(9, deleted);
		setValue(10, deletedUser);
		setValue(11, version);
	}
}
