/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.PersonalSkill;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record3;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 個人スキル
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalSkillRecord extends UpdatableRecordImpl<PersonalSkillRecord> implements Record11<Integer, Integer, Integer, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 168766400;

	/**
	 * Setter for <code>members.personal_skill.user_id</code>. ユーザID
	 */
	public void setUserId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.personal_skill.user_id</code>. ユーザID
	 */
	public Integer getUserId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.personal_skill.skill_type_no</code>. スキル種類番号
	 */
	public void setSkillTypeNo(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.personal_skill.skill_type_no</code>. スキル種類番号
	 */
	public Integer getSkillTypeNo() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.personal_skill.skill_no</code>. スキル番号
	 */
	public void setSkillNo(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.personal_skill.skill_no</code>. スキル番号
	 */
	public Integer getSkillNo() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>members.personal_skill.comment</code>. コメント
	 */
	public void setComment(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.personal_skill.comment</code>. コメント
	 */
	public String getComment() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>members.personal_skill.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.personal_skill.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>members.personal_skill.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.personal_skill.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>members.personal_skill.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.personal_skill.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>members.personal_skill.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.personal_skill.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>members.personal_skill.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.personal_skill.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>members.personal_skill.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.personal_skill.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>members.personal_skill.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.personal_skill.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record3<Integer, Integer, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Integer, Integer, Integer, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return PersonalSkill.PERSONAL_SKILL.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return PersonalSkill.PERSONAL_SKILL.SKILL_TYPE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return PersonalSkill.PERSONAL_SKILL.SKILL_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return PersonalSkill.PERSONAL_SKILL.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return PersonalSkill.PERSONAL_SKILL.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return PersonalSkill.PERSONAL_SKILL.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return PersonalSkill.PERSONAL_SKILL.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return PersonalSkill.PERSONAL_SKILL.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return PersonalSkill.PERSONAL_SKILL.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return PersonalSkill.PERSONAL_SKILL.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return PersonalSkill.PERSONAL_SKILL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSkillTypeNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSkillNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value1(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value2(Integer value) {
		setSkillTypeNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value3(Integer value) {
		setSkillNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value4(String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value5(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value6(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value7(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value8(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value9(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value10(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord value11(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkillRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5, Integer value6, Timestamp value7, Integer value8, Timestamp value9, Integer value10, Integer value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonalSkillRecord
	 */
	public PersonalSkillRecord() {
		super(PersonalSkill.PERSONAL_SKILL);
	}

	/**
	 * Create a detached, initialised PersonalSkillRecord
	 */
	public PersonalSkillRecord(Integer userId, Integer skillTypeNo, Integer skillNo, String comment, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(PersonalSkill.PERSONAL_SKILL);

		setValue(0, userId);
		setValue(1, skillTypeNo);
		setValue(2, skillNo);
		setValue(3, comment);
		setValue(4, created);
		setValue(5, createdUser);
		setValue(6, updated);
		setValue(7, updatedUser);
		setValue(8, deleted);
		setValue(9, deletedUser);
		setValue(10, version);
	}
}
