/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.Post;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 職位
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostRecord extends UpdatableRecordImpl<PostRecord> implements Record2<String, String> {

	private static final long serialVersionUID = -1865931778;

	/**
	 * Setter for <code>members.post.post_cd</code>. 職位コード
	 */
	public void setPostCd(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.post.post_cd</code>. 職位コード
	 */
	public String getPostCd() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>members.post.name</code>. 職位名
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.post.name</code>. 職位名
	 */
	public String getName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return Post.POST.POST_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Post.POST.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPostCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value1(String value) {
		setPostCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PostRecord values(String value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PostRecord
	 */
	public PostRecord() {
		super(Post.POST);
	}

	/**
	 * Create a detached, initialised PostRecord
	 */
	public PostRecord(String postCd, String name) {
		super(Post.POST);

		setValue(0, postCd);
		setValue(1, name);
	}
}
