/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.RelateUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 連係用ユーザ情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelateUserRecord extends UpdatableRecordImpl<RelateUserRecord> implements Record3<Integer, Integer, String> {

	private static final long serialVersionUID = -1191924694;

	/**
	 * Setter for <code>members.relate_user.id</code>. ID
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.relate_user.id</code>. ID
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.relate_user.user_id</code>. ユーザID
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.relate_user.user_id</code>. ユーザID
	 */
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>members.relate_user.zaimu_user_id</code>. 財務ユーザID
	 */
	public void setZaimuUserId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.relate_user.zaimu_user_id</code>. 財務ユーザID
	 */
	public String getZaimuUserId() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RelateUser.RELATE_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return RelateUser.RELATE_USER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RelateUser.RELATE_USER.ZAIMU_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getZaimuUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateUserRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateUserRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateUserRecord value3(String value) {
		setZaimuUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateUserRecord values(Integer value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RelateUserRecord
	 */
	public RelateUserRecord() {
		super(RelateUser.RELATE_USER);
	}

	/**
	 * Create a detached, initialised RelateUserRecord
	 */
	public RelateUserRecord(Integer id, Integer userId, String zaimuUserId) {
		super(RelateUser.RELATE_USER);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, zaimuUserId);
	}
}
