/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.RelateDepartment;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 連係用部署情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelateDepartmentRecord extends UpdatableRecordImpl<RelateDepartmentRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = -1765486257;

	/**
	 * Setter for <code>members.relate_department.id</code>. ID
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.relate_department.id</code>. ID
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.relate_department.dept_cd</code>. 部署コード
	 */
	public void setDeptCd(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.relate_department.dept_cd</code>. 部署コード
	 */
	public String getDeptCd() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.relate_department.sagyo_cd</code>. 財務作業所コード
	 */
	public void setSagyoCd(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.relate_department.sagyo_cd</code>. 財務作業所コード
	 */
	public String getSagyoCd() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RelateDepartment.RELATE_DEPARTMENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return RelateDepartment.RELATE_DEPARTMENT.DEPT_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RelateDepartment.RELATE_DEPARTMENT.SAGYO_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDeptCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSagyoCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateDepartmentRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateDepartmentRecord value2(String value) {
		setDeptCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateDepartmentRecord value3(String value) {
		setSagyoCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelateDepartmentRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RelateDepartmentRecord
	 */
	public RelateDepartmentRecord() {
		super(RelateDepartment.RELATE_DEPARTMENT);
	}

	/**
	 * Create a detached, initialised RelateDepartmentRecord
	 */
	public RelateDepartmentRecord(Integer id, String deptCd, String sagyoCd) {
		super(RelateDepartment.RELATE_DEPARTMENT);

		setValue(0, id);
		setValue(1, deptCd);
		setValue(2, sagyoCd);
	}
}
