/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.School;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 学校
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchoolRecord extends UpdatableRecordImpl<SchoolRecord> implements Record12<Integer, String, String, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = 1112491239;

	/**
	 * Setter for <code>members.school.school_id</code>. 学校コード
	 */
	public void setSchoolId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.school.school_id</code>. 学校コード
	 */
	public Integer getSchoolId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.school.school_name</code>. 学校名
	 */
	public void setSchoolName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.school.school_name</code>. 学校名
	 */
	public String getSchoolName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.school.school_type</code>. 学校区分
	 */
	public void setSchoolType(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.school.school_type</code>. 学校区分
	 */
	public String getSchoolType() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.school.pref_cd</code>. 所在県
	 */
	public void setPrefCd(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.school.pref_cd</code>. 所在県
	 */
	public String getPrefCd() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>members.school.comment</code>. コメント
	 */
	public void setComment(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.school.comment</code>. コメント
	 */
	public String getComment() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>members.school.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.school.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>members.school.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.school.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>members.school.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.school.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>members.school.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.school.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>members.school.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.school.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>members.school.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.school.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>members.school.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.school.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, String, String, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<Integer, String, String, String, String, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return School.SCHOOL.SCHOOL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return School.SCHOOL.SCHOOL_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return School.SCHOOL.SCHOOL_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return School.SCHOOL.PREF_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return School.SCHOOL.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return School.SCHOOL.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return School.SCHOOL.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return School.SCHOOL.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return School.SCHOOL.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return School.SCHOOL.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return School.SCHOOL.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return School.SCHOOL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getSchoolId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSchoolName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSchoolType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPrefCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value1(Integer value) {
		setSchoolId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value2(String value) {
		setSchoolName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value3(String value) {
		setSchoolType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value4(String value) {
		setPrefCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value5(String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value6(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value7(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value8(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value9(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value10(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value11(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord value12(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchoolRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Integer value7, Timestamp value8, Integer value9, Timestamp value10, Integer value11, Integer value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SchoolRecord
	 */
	public SchoolRecord() {
		super(School.SCHOOL);
	}

	/**
	 * Create a detached, initialised SchoolRecord
	 */
	public SchoolRecord(Integer schoolId, String schoolName, String schoolType, String prefCd, String comment, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(School.SCHOOL);

		setValue(0, schoolId);
		setValue(1, schoolName);
		setValue(2, schoolType);
		setValue(3, prefCd);
		setValue(4, comment);
		setValue(5, created);
		setValue(6, createdUser);
		setValue(7, updated);
		setValue(8, updatedUser);
		setValue(9, deleted);
		setValue(10, deletedUser);
		setValue(11, version);
	}
}
