/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.Skill;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * スキル
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkillRecord extends UpdatableRecordImpl<SkillRecord> implements Record15<Integer, String, String, Integer, String, Byte, String, Integer, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> {

	private static final long serialVersionUID = -790917279;

	/**
	 * Setter for <code>members.skill.skill_no</code>. スキル番号
	 */
	public void setSkillNo(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.skill.skill_no</code>. スキル番号
	 */
	public Integer getSkillNo() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.skill.name</code>. スキル名称
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.skill.name</code>. スキル名称
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.skill.short_name</code>. スキル略称
	 */
	public void setShortName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.skill.short_name</code>. スキル略称
	 */
	public String getShortName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.skill.skill_type_no</code>. スキル種類番号
	 */
	public void setSkillTypeNo(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.skill.skill_type_no</code>. スキル種類番号
	 */
	public Integer getSkillTypeNo() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>members.skill.level</code>. スキル階層
	 */
	public void setLevel(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.skill.level</code>. スキル階層
	 */
	public String getLevel() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>members.skill.is_category</code>. カテゴリ識別
	 */
	public void setIsCategory(Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.skill.is_category</code>. カテゴリ識別
	 */
	public Byte getIsCategory() {
		return (Byte) getValue(5);
	}

	/**
	 * Setter for <code>members.skill.comment</code>. コメント
	 */
	public void setComment(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.skill.comment</code>. コメント
	 */
	public String getComment() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>members.skill.sortkey</code>. 並び順
	 */
	public void setSortkey(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.skill.sortkey</code>. 並び順
	 */
	public Integer getSortkey() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>members.skill.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.skill.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>members.skill.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.skill.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>members.skill.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.skill.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>members.skill.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.skill.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>members.skill.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>members.skill.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>members.skill.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>members.skill.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(13);
	}

	/**
	 * Setter for <code>members.skill.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>members.skill.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<Integer, String, String, Integer, String, Byte, String, Integer, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> fieldsRow() {
		return (Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row15<Integer, String, String, Integer, String, Byte, String, Integer, Timestamp, Integer, Timestamp, Integer, Timestamp, Integer, Integer> valuesRow() {
		return (Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Skill.SKILL.SKILL_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Skill.SKILL.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Skill.SKILL.SHORT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Skill.SKILL.SKILL_TYPE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Skill.SKILL.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field6() {
		return Skill.SKILL.IS_CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Skill.SKILL.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Skill.SKILL.SORTKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return Skill.SKILL.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Skill.SKILL.CREATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return Skill.SKILL.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Skill.SKILL.UPDATED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field13() {
		return Skill.SKILL.DELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field14() {
		return Skill.SKILL.DELETED_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return Skill.SKILL.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getSkillNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getShortName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getSkillTypeNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value6() {
		return getIsCategory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getSortkey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getCreatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getUpdatedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value13() {
		return getDeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value14() {
		return getDeletedUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value1(Integer value) {
		setSkillNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value3(String value) {
		setShortName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value4(Integer value) {
		setSkillTypeNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value5(String value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value6(Byte value) {
		setIsCategory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value7(String value) {
		setComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value8(Integer value) {
		setSortkey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value9(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value10(Integer value) {
		setCreatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value11(Timestamp value) {
		setUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value12(Integer value) {
		setUpdatedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value13(Timestamp value) {
		setDeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value14(Integer value) {
		setDeletedUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord value15(Integer value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SkillRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Byte value6, String value7, Integer value8, Timestamp value9, Integer value10, Timestamp value11, Integer value12, Timestamp value13, Integer value14, Integer value15) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SkillRecord
	 */
	public SkillRecord() {
		super(Skill.SKILL);
	}

	/**
	 * Create a detached, initialised SkillRecord
	 */
	public SkillRecord(Integer skillNo, String name, String shortName, Integer skillTypeNo, String level, Byte isCategory, String comment, Integer sortkey, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(Skill.SKILL);

		setValue(0, skillNo);
		setValue(1, name);
		setValue(2, shortName);
		setValue(3, skillTypeNo);
		setValue(4, level);
		setValue(5, isCategory);
		setValue(6, comment);
		setValue(7, sortkey);
		setValue(8, created);
		setValue(9, createdUser);
		setValue(10, updated);
		setValue(11, updatedUser);
		setValue(12, deleted);
		setValue(13, deletedUser);
		setValue(14, version);
	}
}
