/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.tables.UserInfo;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * ユーザ情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> {

	private static final long serialVersionUID = 887538055;

	/**
	 * Setter for <code>members.user_info.user_id</code>. ユーザID
	 */
	public void setUserId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>members.user_info.user_id</code>. ユーザID
	 */
	public Integer getUserId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>members.user_info.account</code>. アカウント
	 */
	public void setAccount(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>members.user_info.account</code>. アカウント
	 */
	public String getAccount() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>members.user_info.password</code>. パスワード
	 */
	public void setPassword(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>members.user_info.password</code>. パスワード
	 */
	public String getPassword() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>members.user_info.lastname</code>. 姓
	 */
	public void setLastname(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>members.user_info.lastname</code>. 姓
	 */
	public String getLastname() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>members.user_info.firstname</code>. 名
	 */
	public void setFirstname(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>members.user_info.firstname</code>. 名
	 */
	public String getFirstname() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>members.user_info.lastname_kana</code>. 姓フリガナ
	 */
	public void setLastnameKana(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>members.user_info.lastname_kana</code>. 姓フリガナ
	 */
	public String getLastnameKana() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>members.user_info.firstname_kana</code>. 名フリガナ
	 */
	public void setFirstnameKana(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>members.user_info.firstname_kana</code>. 名フリガナ
	 */
	public String getFirstnameKana() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>members.user_info.gender_cd</code>. 性別コード
	 */
	public void setGenderCd(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>members.user_info.gender_cd</code>. 性別コード
	 */
	public String getGenderCd() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>members.user_info.birthday</code>. 生年月日
	 */
	public void setBirthday(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>members.user_info.birthday</code>. 生年月日
	 */
	public Date getBirthday() {
		return (Date) getValue(8);
	}

	/**
	 * Setter for <code>members.user_info.address1</code>. 住所1
	 */
	public void setAddress1(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>members.user_info.address1</code>. 住所1
	 */
	public String getAddress1() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>members.user_info.address2</code>. 住所2
	 */
	public void setAddress2(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>members.user_info.address2</code>. 住所2
	 */
	public String getAddress2() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>members.user_info.access</code>. 最寄駅バス停
	 */
	public void setAccess(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>members.user_info.access</code>. 最寄駅バス停
	 */
	public String getAccess() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>members.user_info.join_years</code>. 入社年月日
	 */
	public void setJoinYears(Date value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>members.user_info.join_years</code>. 入社年月日
	 */
	public Date getJoinYears() {
		return (Date) getValue(12);
	}

	/**
	 * Setter for <code>members.user_info.dept_cd</code>. 部署コード
	 */
	public void setDeptCd(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>members.user_info.dept_cd</code>. 部署コード
	 */
	public String getDeptCd() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>members.user_info.post_cd</code>. 職位コード
	 */
	public void setPostCd(String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>members.user_info.post_cd</code>. 職位コード
	 */
	public String getPostCd() {
		return (String) getValue(14);
	}

	/**
	 * Setter for <code>members.user_info.auth_cd</code>. 権限コード
	 */
	public void setAuthCd(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>members.user_info.auth_cd</code>. 権限コード
	 */
	public String getAuthCd() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>members.user_info.created</code>. 登録日時
	 */
	public void setCreated(Timestamp value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>members.user_info.created</code>. 登録日時
	 */
	public Timestamp getCreated() {
		return (Timestamp) getValue(16);
	}

	/**
	 * Setter for <code>members.user_info.created_user</code>. 登録ユーザ
	 */
	public void setCreatedUser(Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>members.user_info.created_user</code>. 登録ユーザ
	 */
	public Integer getCreatedUser() {
		return (Integer) getValue(17);
	}

	/**
	 * Setter for <code>members.user_info.updated</code>. 更新日時
	 */
	public void setUpdated(Timestamp value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>members.user_info.updated</code>. 更新日時
	 */
	public Timestamp getUpdated() {
		return (Timestamp) getValue(18);
	}

	/**
	 * Setter for <code>members.user_info.updated_user</code>. 更新ユーザ
	 */
	public void setUpdatedUser(Integer value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>members.user_info.updated_user</code>. 更新ユーザ
	 */
	public Integer getUpdatedUser() {
		return (Integer) getValue(19);
	}

	/**
	 * Setter for <code>members.user_info.deleted</code>. 削除日時
	 */
	public void setDeleted(Timestamp value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>members.user_info.deleted</code>. 削除日時
	 */
	public Timestamp getDeleted() {
		return (Timestamp) getValue(20);
	}

	/**
	 * Setter for <code>members.user_info.deleted_user</code>. 削除ユーザ
	 */
	public void setDeletedUser(Integer value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>members.user_info.deleted_user</code>. 削除ユーザ
	 */
	public Integer getDeletedUser() {
		return (Integer) getValue(21);
	}

	/**
	 * Setter for <code>members.user_info.version</code>. バージョン
	 */
	public void setVersion(Integer value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>members.user_info.version</code>. バージョン
	 */
	public Integer getVersion() {
		return (Integer) getValue(22);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserInfoRecord
	 */
	public UserInfoRecord() {
		super(UserInfo.USER_INFO);
	}

	/**
	 * Create a detached, initialised UserInfoRecord
	 */
	public UserInfoRecord(Integer userId, String account, String password, String lastname, String firstname, String lastnameKana, String firstnameKana, String genderCd, Date birthday, String address1, String address2, String access, Date joinYears, String deptCd, String postCd, String authCd, Timestamp created, Integer createdUser, Timestamp updated, Integer updatedUser, Timestamp deleted, Integer deletedUser, Integer version) {
		super(UserInfo.USER_INFO);

		setValue(0, userId);
		setValue(1, account);
		setValue(2, password);
		setValue(3, lastname);
		setValue(4, firstname);
		setValue(5, lastnameKana);
		setValue(6, firstnameKana);
		setValue(7, genderCd);
		setValue(8, birthday);
		setValue(9, address1);
		setValue(10, address2);
		setValue(11, access);
		setValue(12, joinYears);
		setValue(13, deptCd);
		setValue(14, postCd);
		setValue(15, authCd);
		setValue(16, created);
		setValue(17, createdUser);
		setValue(18, updated);
		setValue(19, updatedUser);
		setValue(20, deleted);
		setValue(21, deletedUser);
		setValue(22, version);
	}
}
