/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.AdToJapaneseYearRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 西暦和暦
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdToJapaneseYear extends TableImpl<AdToJapaneseYearRecord> {

	private static final long serialVersionUID = -872863452;

	/**
	 * The reference instance of <code>members.ad_to_japanese_year</code>
	 */
	public static final AdToJapaneseYear AD_TO_JAPANESE_YEAR = new AdToJapaneseYear();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AdToJapaneseYearRecord> getRecordType() {
		return AdToJapaneseYearRecord.class;
	}

	/**
	 * The column <code>members.ad_to_japanese_year.ad</code>. 西暦
	 */
	public final TableField<AdToJapaneseYearRecord, Integer> AD = createField("ad", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "西暦");

	/**
	 * The column <code>members.ad_to_japanese_year.japanese_year</code>. 和暦
	 */
	public final TableField<AdToJapaneseYearRecord, String> JAPANESE_YEAR = createField("japanese_year", org.jooq.impl.SQLDataType.VARCHAR.length(6), this, "和暦");

	/**
	 * Create a <code>members.ad_to_japanese_year</code> table reference
	 */
	public AdToJapaneseYear() {
		this("ad_to_japanese_year", null);
	}

	/**
	 * Create an aliased <code>members.ad_to_japanese_year</code> table reference
	 */
	public AdToJapaneseYear(String alias) {
		this(alias, AD_TO_JAPANESE_YEAR);
	}

	private AdToJapaneseYear(String alias, Table<AdToJapaneseYearRecord> aliased) {
		this(alias, aliased, null);
	}

	private AdToJapaneseYear(String alias, Table<AdToJapaneseYearRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "西暦和暦");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AdToJapaneseYearRecord> getPrimaryKey() {
		return Keys.KEY_AD_TO_JAPANESE_YEAR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AdToJapaneseYearRecord>> getKeys() {
		return Arrays.<UniqueKey<AdToJapaneseYearRecord>>asList(Keys.KEY_AD_TO_JAPANESE_YEAR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AdToJapaneseYear as(String alias) {
		return new AdToJapaneseYear(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AdToJapaneseYear rename(String name) {
		return new AdToJapaneseYear(name, null);
	}
}
