/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.AnalysisUserInfoRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 分析ユーザ情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisUserInfo extends TableImpl<AnalysisUserInfoRecord> {

	private static final long serialVersionUID = 181669528;

	/**
	 * The reference instance of <code>members.analysis_user_info</code>
	 */
	public static final AnalysisUserInfo ANALYSIS_USER_INFO = new AnalysisUserInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnalysisUserInfoRecord> getRecordType() {
		return AnalysisUserInfoRecord.class;
	}

	/**
	 * The column <code>members.analysis_user_info.user_id</code>. ユーザID
	 */
	public final TableField<AnalysisUserInfoRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "ユーザID");

	/**
	 * The column <code>members.analysis_user_info.select_projects</code>. 選択プロジェクト
	 */
	public final TableField<AnalysisUserInfoRecord, String> SELECT_PROJECTS = createField("select_projects", org.jooq.impl.SQLDataType.CLOB, this, "選択プロジェクト");

	/**
	 * Create a <code>members.analysis_user_info</code> table reference
	 */
	public AnalysisUserInfo() {
		this("analysis_user_info", null);
	}

	/**
	 * Create an aliased <code>members.analysis_user_info</code> table reference
	 */
	public AnalysisUserInfo(String alias) {
		this(alias, ANALYSIS_USER_INFO);
	}

	private AnalysisUserInfo(String alias, Table<AnalysisUserInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private AnalysisUserInfo(String alias, Table<AnalysisUserInfoRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "分析ユーザ情報");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AnalysisUserInfoRecord> getPrimaryKey() {
		return Keys.KEY_ANALYSIS_USER_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AnalysisUserInfoRecord>> getKeys() {
		return Arrays.<UniqueKey<AnalysisUserInfoRecord>>asList(Keys.KEY_ANALYSIS_USER_INFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisUserInfo as(String alias) {
		return new AnalysisUserInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AnalysisUserInfo rename(String name) {
		return new AnalysisUserInfo(name, null);
	}
}
