/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.AnalysisBushoRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 分析部署
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisBusho extends TableImpl<AnalysisBushoRecord> {

	private static final long serialVersionUID = 2142542790;

	/**
	 * The reference instance of <code>members.analysis_busho</code>
	 */
	public static final AnalysisBusho ANALYSIS_BUSHO = new AnalysisBusho();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnalysisBushoRecord> getRecordType() {
		return AnalysisBushoRecord.class;
	}

	/**
	 * The column <code>members.analysis_busho.busho_code</code>. 部署コード
	 */
	public final TableField<AnalysisBushoRecord, String> BUSHO_CODE = createField("busho_code", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "部署コード");

	/**
	 * The column <code>members.analysis_busho.busho_name</code>. 部署名
	 */
	public final TableField<AnalysisBushoRecord, String> BUSHO_NAME = createField("busho_name", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "部署名");

	/**
	 * Create a <code>members.analysis_busho</code> table reference
	 */
	public AnalysisBusho() {
		this("analysis_busho", null);
	}

	/**
	 * Create an aliased <code>members.analysis_busho</code> table reference
	 */
	public AnalysisBusho(String alias) {
		this(alias, ANALYSIS_BUSHO);
	}

	private AnalysisBusho(String alias, Table<AnalysisBushoRecord> aliased) {
		this(alias, aliased, null);
	}

	private AnalysisBusho(String alias, Table<AnalysisBushoRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "分析部署");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AnalysisBushoRecord> getPrimaryKey() {
		return Keys.KEY_ANALYSIS_BUSHO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AnalysisBushoRecord>> getKeys() {
		return Arrays.<UniqueKey<AnalysisBushoRecord>>asList(Keys.KEY_ANALYSIS_BUSHO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisBusho as(String alias) {
		return new AnalysisBusho(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AnalysisBusho rename(String name) {
		return new AnalysisBusho(name, null);
	}
}
