/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.AnalysisProjectSummaryRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 分析プロジェクト集計
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisProjectSummary extends TableImpl<AnalysisProjectSummaryRecord> {

	private static final long serialVersionUID = -1008020447;

	/**
	 * The reference instance of <code>members.analysis_project_summary</code>
	 */
	public static final AnalysisProjectSummary ANALYSIS_PROJECT_SUMMARY = new AnalysisProjectSummary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnalysisProjectSummaryRecord> getRecordType() {
		return AnalysisProjectSummaryRecord.class;
	}

	/**
	 * The column <code>members.analysis_project_summary.project_code</code>. プロジェクトコード
	 */
	public final TableField<AnalysisProjectSummaryRecord, String> PROJECT_CODE = createField("project_code", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "プロジェクトコード");

	/**
	 * The column <code>members.analysis_project_summary.ukeoi_kingaku_with_tax</code>. 請負金額税込
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> UKEOI_KINGAKU_WITH_TAX = createField("ukeoi_kingaku_with_tax", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "請負金額税込");

	/**
	 * The column <code>members.analysis_project_summary.ukeoi_kingaku</code>. 請負金額
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> UKEOI_KINGAKU = createField("ukeoi_kingaku", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "請負金額");

	/**
	 * The column <code>members.analysis_project_summary.yosan_shiire</code>. 予算仕入
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> YOSAN_SHIIRE = createField("yosan_shiire", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "予算仕入");

	/**
	 * The column <code>members.analysis_project_summary.yosan_gaichu</code>. 予算外注
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> YOSAN_GAICHU = createField("yosan_gaichu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "予算外注");

	/**
	 * The column <code>members.analysis_project_summary.yosan_dev</code>. 予算開発
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> YOSAN_DEV = createField("yosan_dev", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "予算開発");

	/**
	 * The column <code>members.analysis_project_summary.yosan_rieki</code>. 予算利益
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> YOSAN_RIEKI = createField("yosan_rieki", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "予算利益");

	/**
	 * The column <code>members.analysis_project_summary.jisseki_uriage</code>. 実績売上
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> JISSEKI_URIAGE = createField("jisseki_uriage", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績売上");

	/**
	 * The column <code>members.analysis_project_summary.jisseki_shiire</code>. 実績原価仕入
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> JISSEKI_SHIIRE = createField("jisseki_shiire", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価仕入");

	/**
	 * The column <code>members.analysis_project_summary.jisseki_roumu</code>. 実績原価労務
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> JISSEKI_ROUMU = createField("jisseki_roumu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価労務");

	/**
	 * The column <code>members.analysis_project_summary.jisseki_gaichu</code>. 実績原価外注
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> JISSEKI_GAICHU = createField("jisseki_gaichu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価外注");

	/**
	 * The column <code>members.analysis_project_summary.jisseki_keihi</code>. 実績原価経費
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> JISSEKI_KEIHI = createField("jisseki_keihi", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価経費");

	/**
	 * The column <code>members.analysis_project_summary.work_time</code>. 稼働時間通常
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> WORK_TIME = createField("work_time", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間通常");

	/**
	 * The column <code>members.analysis_project_summary.work_time_jikangai</code>. 稼働時間時間外
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> WORK_TIME_JIKANGAI = createField("work_time_jikangai", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間時間外");

	/**
	 * The column <code>members.analysis_project_summary.work_time_kyujitsu</code>. 稼働時間休日
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> WORK_TIME_KYUJITSU = createField("work_time_kyujitsu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間休日");

	/**
	 * The column <code>members.analysis_project_summary.work_time_houteigai</code>. 稼働時間法定外
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> WORK_TIME_HOUTEIGAI = createField("work_time_houteigai", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間法定外");

	/**
	 * The column <code>members.analysis_project_summary.work_time_sinya</code>. 稼働時間深夜
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> WORK_TIME_SINYA = createField("work_time_sinya", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間深夜");

	/**
	 * The column <code>members.analysis_project_summary.work_time_houteigai_sinya</code>. 稼働時間法定外深夜
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> WORK_TIME_HOUTEIGAI_SINYA = createField("work_time_houteigai_sinya", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間法定外深夜");

	/**
	 * The column <code>members.analysis_project_summary.record_time</code>. 稼働時間記録
	 */
	public final TableField<AnalysisProjectSummaryRecord, BigDecimal> RECORD_TIME = createField("record_time", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間記録");

	/**
	 * Create a <code>members.analysis_project_summary</code> table reference
	 */
	public AnalysisProjectSummary() {
		this("analysis_project_summary", null);
	}

	/**
	 * Create an aliased <code>members.analysis_project_summary</code> table reference
	 */
	public AnalysisProjectSummary(String alias) {
		this(alias, ANALYSIS_PROJECT_SUMMARY);
	}

	private AnalysisProjectSummary(String alias, Table<AnalysisProjectSummaryRecord> aliased) {
		this(alias, aliased, null);
	}

	private AnalysisProjectSummary(String alias, Table<AnalysisProjectSummaryRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "分析プロジェクト集計");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AnalysisProjectSummaryRecord> getPrimaryKey() {
		return Keys.KEY_ANALYSIS_PROJECT_SUMMARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AnalysisProjectSummaryRecord>> getKeys() {
		return Arrays.<UniqueKey<AnalysisProjectSummaryRecord>>asList(Keys.KEY_ANALYSIS_PROJECT_SUMMARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectSummary as(String alias) {
		return new AnalysisProjectSummary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AnalysisProjectSummary rename(String name) {
		return new AnalysisProjectSummary(name, null);
	}
}
