/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.AnalysisProjectMonthlySummaryRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 分析プロジェクト月別集計
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisProjectMonthlySummary extends TableImpl<AnalysisProjectMonthlySummaryRecord> {

	private static final long serialVersionUID = -663008487;

	/**
	 * The reference instance of <code>members.analysis_project_monthly_summary</code>
	 */
	public static final AnalysisProjectMonthlySummary ANALYSIS_PROJECT_MONTHLY_SUMMARY = new AnalysisProjectMonthlySummary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnalysisProjectMonthlySummaryRecord> getRecordType() {
		return AnalysisProjectMonthlySummaryRecord.class;
	}

	/**
	 * The column <code>members.analysis_project_monthly_summary.project_code</code>. プロジェクトコード
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, String> PROJECT_CODE = createField("project_code", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "プロジェクトコード");

	/**
	 * The column <code>members.analysis_project_monthly_summary.nendo</code>. 稼働年度
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, Integer> NENDO = createField("nendo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "稼働年度");

	/**
	 * The column <code>members.analysis_project_monthly_summary.month_no</code>. 稼働月数
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, Integer> MONTH_NO = createField("month_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "稼働月数");

	/**
	 * The column <code>members.analysis_project_monthly_summary.ym</code>. 年月
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, String> YM = createField("ym", org.jooq.impl.SQLDataType.VARCHAR.length(6).nullable(false), this, "年月");

	/**
	 * The column <code>members.analysis_project_monthly_summary.jisseki_uriage</code>. 実績売上
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> JISSEKI_URIAGE = createField("jisseki_uriage", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績売上");

	/**
	 * The column <code>members.analysis_project_monthly_summary.jisseki_shiire</code>. 実績原価仕入
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> JISSEKI_SHIIRE = createField("jisseki_shiire", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価仕入");

	/**
	 * The column <code>members.analysis_project_monthly_summary.jisseki_roumu</code>. 実績原価労務
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> JISSEKI_ROUMU = createField("jisseki_roumu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価労務");

	/**
	 * The column <code>members.analysis_project_monthly_summary.jisseki_gaichu</code>. 実績原価外注
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> JISSEKI_GAICHU = createField("jisseki_gaichu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価外注");

	/**
	 * The column <code>members.analysis_project_monthly_summary.jisseki_keihi</code>. 実績原価経費
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> JISSEKI_KEIHI = createField("jisseki_keihi", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "実績原価経費");

	/**
	 * The column <code>members.analysis_project_monthly_summary.work_time</code>. 稼働時間通常
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> WORK_TIME = createField("work_time", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間通常");

	/**
	 * The column <code>members.analysis_project_monthly_summary.work_time_jikangai</code>. 稼働時間時間外
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> WORK_TIME_JIKANGAI = createField("work_time_jikangai", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間時間外");

	/**
	 * The column <code>members.analysis_project_monthly_summary.work_time_kyujitsu</code>. 稼働時間休日
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> WORK_TIME_KYUJITSU = createField("work_time_kyujitsu", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間休日");

	/**
	 * The column <code>members.analysis_project_monthly_summary.work_time_houteigai</code>. 稼働時間法定外
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> WORK_TIME_HOUTEIGAI = createField("work_time_houteigai", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間法定外");

	/**
	 * The column <code>members.analysis_project_monthly_summary.work_time_sinya</code>. 稼働時間深夜
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> WORK_TIME_SINYA = createField("work_time_sinya", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間深夜");

	/**
	 * The column <code>members.analysis_project_monthly_summary.work_time_houteigai_sinya</code>. 稼働時間法定外深夜
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> WORK_TIME_HOUTEIGAI_SINYA = createField("work_time_houteigai_sinya", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間法定外深夜");

	/**
	 * The column <code>members.analysis_project_monthly_summary.record_time</code>. 稼働時間記録
	 */
	public final TableField<AnalysisProjectMonthlySummaryRecord, BigDecimal> RECORD_TIME = createField("record_time", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 3), this, "稼働時間記録");

	/**
	 * Create a <code>members.analysis_project_monthly_summary</code> table reference
	 */
	public AnalysisProjectMonthlySummary() {
		this("analysis_project_monthly_summary", null);
	}

	/**
	 * Create an aliased <code>members.analysis_project_monthly_summary</code> table reference
	 */
	public AnalysisProjectMonthlySummary(String alias) {
		this(alias, ANALYSIS_PROJECT_MONTHLY_SUMMARY);
	}

	private AnalysisProjectMonthlySummary(String alias, Table<AnalysisProjectMonthlySummaryRecord> aliased) {
		this(alias, aliased, null);
	}

	private AnalysisProjectMonthlySummary(String alias, Table<AnalysisProjectMonthlySummaryRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "分析プロジェクト月別集計");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AnalysisProjectMonthlySummaryRecord> getPrimaryKey() {
		return Keys.KEY_ANALYSIS_PROJECT_MONTHLY_SUMMARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AnalysisProjectMonthlySummaryRecord>> getKeys() {
		return Arrays.<UniqueKey<AnalysisProjectMonthlySummaryRecord>>asList(Keys.KEY_ANALYSIS_PROJECT_MONTHLY_SUMMARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisProjectMonthlySummary as(String alias) {
		return new AnalysisProjectMonthlySummary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AnalysisProjectMonthlySummary rename(String name) {
		return new AnalysisProjectMonthlySummary(name, null);
	}
}
