/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.AnalysisCustomerRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 分析取引先
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnalysisCustomer extends TableImpl<AnalysisCustomerRecord> {

	private static final long serialVersionUID = 1713302370;

	/**
	 * The reference instance of <code>members.analysis_customer</code>
	 */
	public static final AnalysisCustomer ANALYSIS_CUSTOMER = new AnalysisCustomer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AnalysisCustomerRecord> getRecordType() {
		return AnalysisCustomerRecord.class;
	}

	/**
	 * The column <code>members.analysis_customer.customer_code</code>. 取引先コード
	 */
	public final TableField<AnalysisCustomerRecord, String> CUSTOMER_CODE = createField("customer_code", org.jooq.impl.SQLDataType.VARCHAR.length(8).nullable(false), this, "取引先コード");

	/**
	 * The column <code>members.analysis_customer.customer_name</code>. 取引先名
	 */
	public final TableField<AnalysisCustomerRecord, String> CUSTOMER_NAME = createField("customer_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "取引先名");

	/**
	 * Create a <code>members.analysis_customer</code> table reference
	 */
	public AnalysisCustomer() {
		this("analysis_customer", null);
	}

	/**
	 * Create an aliased <code>members.analysis_customer</code> table reference
	 */
	public AnalysisCustomer(String alias) {
		this(alias, ANALYSIS_CUSTOMER);
	}

	private AnalysisCustomer(String alias, Table<AnalysisCustomerRecord> aliased) {
		this(alias, aliased, null);
	}

	private AnalysisCustomer(String alias, Table<AnalysisCustomerRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "分析取引先");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AnalysisCustomerRecord> getPrimaryKey() {
		return Keys.KEY_ANALYSIS_CUSTOMER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AnalysisCustomerRecord>> getKeys() {
		return Arrays.<UniqueKey<AnalysisCustomerRecord>>asList(Keys.KEY_ANALYSIS_CUSTOMER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AnalysisCustomer as(String alias) {
		return new AnalysisCustomer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AnalysisCustomer rename(String name) {
		return new AnalysisCustomer(name, null);
	}
}
