/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.CareerDetailSkillRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 業務経歴詳細スキル
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CareerDetailSkill extends TableImpl<CareerDetailSkillRecord> {

	private static final long serialVersionUID = 1823537118;

	/**
	 * The reference instance of <code>members.career_detail_skill</code>
	 */
	public static final CareerDetailSkill CAREER_DETAIL_SKILL = new CareerDetailSkill();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CareerDetailSkillRecord> getRecordType() {
		return CareerDetailSkillRecord.class;
	}

	/**
	 * The column <code>members.career_detail_skill.user_id</code>. ユーザID
	 */
	public final TableField<CareerDetailSkillRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "ユーザID");

	/**
	 * The column <code>members.career_detail_skill.job_no</code>. 業務経歴番号
	 */
	public final TableField<CareerDetailSkillRecord, Integer> JOB_NO = createField("job_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "業務経歴番号");

	/**
	 * The column <code>members.career_detail_skill.skill_type_no</code>. スキル種類番号
	 */
	public final TableField<CareerDetailSkillRecord, Integer> SKILL_TYPE_NO = createField("skill_type_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "スキル種類番号");

	/**
	 * The column <code>members.career_detail_skill.no</code>. 連番
	 */
	public final TableField<CareerDetailSkillRecord, Integer> NO = createField("no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "連番");

	/**
	 * The column <code>members.career_detail_skill.skill_no</code>. スキル番号
	 */
	public final TableField<CareerDetailSkillRecord, Integer> SKILL_NO = createField("skill_no", org.jooq.impl.SQLDataType.INTEGER, this, "スキル番号");

	/**
	 * The column <code>members.career_detail_skill.comment</code>. コメント
	 */
	public final TableField<CareerDetailSkillRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "コメント");

	/**
	 * The column <code>members.career_detail_skill.created</code>. 登録日時
	 */
	public final TableField<CareerDetailSkillRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "登録日時");

	/**
	 * The column <code>members.career_detail_skill.created_user</code>. 登録ユーザ
	 */
	public final TableField<CareerDetailSkillRecord, Integer> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.INTEGER, this, "登録ユーザ");

	/**
	 * The column <code>members.career_detail_skill.updated</code>. 更新日時
	 */
	public final TableField<CareerDetailSkillRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新日時");

	/**
	 * The column <code>members.career_detail_skill.updated_user</code>. 更新ユーザ
	 */
	public final TableField<CareerDetailSkillRecord, Integer> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.INTEGER, this, "更新ユーザ");

	/**
	 * The column <code>members.career_detail_skill.deleted</code>. 削除日時
	 */
	public final TableField<CareerDetailSkillRecord, Timestamp> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TIMESTAMP, this, "削除日時");

	/**
	 * The column <code>members.career_detail_skill.deleted_user</code>. 削除ユーザ
	 */
	public final TableField<CareerDetailSkillRecord, Integer> DELETED_USER = createField("deleted_user", org.jooq.impl.SQLDataType.INTEGER, this, "削除ユーザ");

	/**
	 * The column <code>members.career_detail_skill.version</code>. バージョン
	 */
	public final TableField<CareerDetailSkillRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "バージョン");

	/**
	 * Create a <code>members.career_detail_skill</code> table reference
	 */
	public CareerDetailSkill() {
		this("career_detail_skill", null);
	}

	/**
	 * Create an aliased <code>members.career_detail_skill</code> table reference
	 */
	public CareerDetailSkill(String alias) {
		this(alias, CAREER_DETAIL_SKILL);
	}

	private CareerDetailSkill(String alias, Table<CareerDetailSkillRecord> aliased) {
		this(alias, aliased, null);
	}

	private CareerDetailSkill(String alias, Table<CareerDetailSkillRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "業務経歴詳細スキル");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CareerDetailSkillRecord> getPrimaryKey() {
		return Keys.KEY_CAREER_DETAIL_SKILL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CareerDetailSkillRecord>> getKeys() {
		return Arrays.<UniqueKey<CareerDetailSkillRecord>>asList(Keys.KEY_CAREER_DETAIL_SKILL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<CareerDetailSkillRecord, Integer> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetailSkill as(String alias) {
		return new CareerDetailSkill(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CareerDetailSkill rename(String name) {
		return new CareerDetailSkill(name, null);
	}
}
