/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.CareerDetailRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 業務経歴詳細
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CareerDetail extends TableImpl<CareerDetailRecord> {

	private static final long serialVersionUID = -186071453;

	/**
	 * The reference instance of <code>members.career_detail</code>
	 */
	public static final CareerDetail CAREER_DETAIL = new CareerDetail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CareerDetailRecord> getRecordType() {
		return CareerDetailRecord.class;
	}

	/**
	 * The column <code>members.career_detail.user_id</code>. ユーザID
	 */
	public final TableField<CareerDetailRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "ユーザID");

	/**
	 * The column <code>members.career_detail.job_no</code>. 業務経歴番号
	 */
	public final TableField<CareerDetailRecord, Integer> JOB_NO = createField("job_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "業務経歴番号");

	/**
	 * The column <code>members.career_detail.job_name</code>. 担当主要業務
	 */
	public final TableField<CareerDetailRecord, String> JOB_NAME = createField("job_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "担当主要業務");

	/**
	 * The column <code>members.career_detail.span_from</code>. 期間自
	 */
	public final TableField<CareerDetailRecord, String> SPAN_FROM = createField("span_from", org.jooq.impl.SQLDataType.VARCHAR.length(6), this, "期間自");

	/**
	 * The column <code>members.career_detail.span_to</code>. 期間至
	 */
	public final TableField<CareerDetailRecord, String> SPAN_TO = createField("span_to", org.jooq.impl.SQLDataType.VARCHAR.length(6), this, "期間至");

	/**
	 * The column <code>members.career_detail.remark</code>. 備考
	 */
	public final TableField<CareerDetailRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "備考");

	/**
	 * The column <code>members.career_detail.created</code>. 登録日時
	 */
	public final TableField<CareerDetailRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "登録日時");

	/**
	 * The column <code>members.career_detail.created_user</code>. 登録ユーザ
	 */
	public final TableField<CareerDetailRecord, Integer> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.INTEGER, this, "登録ユーザ");

	/**
	 * The column <code>members.career_detail.updated</code>. 更新日時
	 */
	public final TableField<CareerDetailRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新日時");

	/**
	 * The column <code>members.career_detail.updated_user</code>. 更新ユーザ
	 */
	public final TableField<CareerDetailRecord, Integer> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.INTEGER, this, "更新ユーザ");

	/**
	 * The column <code>members.career_detail.deleted</code>. 削除日時
	 */
	public final TableField<CareerDetailRecord, Timestamp> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TIMESTAMP, this, "削除日時");

	/**
	 * The column <code>members.career_detail.deleted_user</code>. 削除ユーザ
	 */
	public final TableField<CareerDetailRecord, Integer> DELETED_USER = createField("deleted_user", org.jooq.impl.SQLDataType.INTEGER, this, "削除ユーザ");

	/**
	 * The column <code>members.career_detail.version</code>. バージョン
	 */
	public final TableField<CareerDetailRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "バージョン");

	/**
	 * Create a <code>members.career_detail</code> table reference
	 */
	public CareerDetail() {
		this("career_detail", null);
	}

	/**
	 * Create an aliased <code>members.career_detail</code> table reference
	 */
	public CareerDetail(String alias) {
		this(alias, CAREER_DETAIL);
	}

	private CareerDetail(String alias, Table<CareerDetailRecord> aliased) {
		this(alias, aliased, null);
	}

	private CareerDetail(String alias, Table<CareerDetailRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "業務経歴詳細");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CareerDetailRecord> getPrimaryKey() {
		return Keys.KEY_CAREER_DETAIL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CareerDetailRecord>> getKeys() {
		return Arrays.<UniqueKey<CareerDetailRecord>>asList(Keys.KEY_CAREER_DETAIL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<CareerDetailRecord, Integer> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CareerDetail as(String alias) {
		return new CareerDetail(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CareerDetail rename(String name) {
		return new CareerDetail(name, null);
	}
}
