/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsAssetAssessRiskRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * アセスメント資産脅威脆弱性
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAssetAssessRisk extends TableImpl<IsmsAssetAssessRiskRecord> {

	private static final long serialVersionUID = 417957451;

	/**
	 * The reference instance of <code>members.isms_asset_assess_risk</code>
	 */
	public static final IsmsAssetAssessRisk ISMS_ASSET_ASSESS_RISK = new IsmsAssetAssessRisk();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsAssetAssessRiskRecord> getRecordType() {
		return IsmsAssetAssessRiskRecord.class;
	}

	/**
	 * The column <code>members.isms_asset_assess_risk.limit_date</code>. 締切日
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Timestamp> LIMIT_DATE = createField("limit_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "締切日");

	/**
	 * The column <code>members.isms_asset_assess_risk.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_asset_assess_risk.threat_weak_id</code>. 脅威脆弱性ID
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> THREAT_WEAK_ID = createField("threat_weak_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "脅威脆弱性ID");

	/**
	 * The column <code>members.isms_asset_assess_risk.threat_name</code>. 脅威名
	 */
	public final TableField<IsmsAssetAssessRiskRecord, String> THREAT_NAME = createField("threat_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "脅威名");

	/**
	 * The column <code>members.isms_asset_assess_risk.threat_confidential</code>. 脅威機密性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> THREAT_CONFIDENTIAL = createField("threat_confidential", org.jooq.impl.SQLDataType.INTEGER, this, "脅威機密性");

	/**
	 * The column <code>members.isms_asset_assess_risk.threat_integrity</code>. 脅威完全性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> THREAT_INTEGRITY = createField("threat_integrity", org.jooq.impl.SQLDataType.INTEGER, this, "脅威完全性");

	/**
	 * The column <code>members.isms_asset_assess_risk.threat_availability</code>. 脅威可用性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> THREAT_AVAILABILITY = createField("threat_availability", org.jooq.impl.SQLDataType.INTEGER, this, "脅威可用性");

	/**
	 * The column <code>members.isms_asset_assess_risk.weak_name</code>. 脆弱性名
	 */
	public final TableField<IsmsAssetAssessRiskRecord, String> WEAK_NAME = createField("weak_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "脆弱性名");

	/**
	 * The column <code>members.isms_asset_assess_risk.weak_confidential</code>. 脆弱性機密性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> WEAK_CONFIDENTIAL = createField("weak_confidential", org.jooq.impl.SQLDataType.INTEGER, this, "脆弱性機密性");

	/**
	 * The column <code>members.isms_asset_assess_risk.weak_integrity</code>. 脆弱性完全性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> WEAK_INTEGRITY = createField("weak_integrity", org.jooq.impl.SQLDataType.INTEGER, this, "脆弱性完全性");

	/**
	 * The column <code>members.isms_asset_assess_risk.weak_availability</code>. 脆弱性可用性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> WEAK_AVAILABILITY = createField("weak_availability", org.jooq.impl.SQLDataType.INTEGER, this, "脆弱性可用性");

	/**
	 * The column <code>members.isms_asset_assess_risk.risk_confidential</code>. リスク値機密性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> RISK_CONFIDENTIAL = createField("risk_confidential", org.jooq.impl.SQLDataType.INTEGER, this, "リスク値機密性");

	/**
	 * The column <code>members.isms_asset_assess_risk.risk_integrity</code>. リスク値完全性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> RISK_INTEGRITY = createField("risk_integrity", org.jooq.impl.SQLDataType.INTEGER, this, "リスク値完全性");

	/**
	 * The column <code>members.isms_asset_assess_risk.risk_availability</code>. リスク値可用性
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> RISK_AVAILABILITY = createField("risk_availability", org.jooq.impl.SQLDataType.INTEGER, this, "リスク値可用性");

	/**
	 * The column <code>members.isms_asset_assess_risk.judge</code>. 受容可否
	 */
	public final TableField<IsmsAssetAssessRiskRecord, Integer> JUDGE = createField("judge", org.jooq.impl.SQLDataType.INTEGER, this, "受容可否");

	/**
	 * The column <code>members.isms_asset_assess_risk.remark</code>. 備考
	 */
	public final TableField<IsmsAssetAssessRiskRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "備考");

	/**
	 * Create a <code>members.isms_asset_assess_risk</code> table reference
	 */
	public IsmsAssetAssessRisk() {
		this("isms_asset_assess_risk", null);
	}

	/**
	 * Create an aliased <code>members.isms_asset_assess_risk</code> table reference
	 */
	public IsmsAssetAssessRisk(String alias) {
		this(alias, ISMS_ASSET_ASSESS_RISK);
	}

	private IsmsAssetAssessRisk(String alias, Table<IsmsAssetAssessRiskRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsAssetAssessRisk(String alias, Table<IsmsAssetAssessRiskRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "アセスメント資産脅威脆弱性");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsAssetAssessRiskRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_ASSET_ASSESS_RISK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsAssetAssessRiskRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsAssetAssessRiskRecord>>asList(Keys.KEY_ISMS_ASSET_ASSESS_RISK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssessRisk as(String alias) {
		return new IsmsAssetAssessRisk(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsAssetAssessRisk rename(String name) {
		return new IsmsAssetAssessRisk(name, null);
	}
}
