/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsStoreOutRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 入出庫管理台帳出庫
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsStoreOut extends TableImpl<IsmsStoreOutRecord> {

	private static final long serialVersionUID = -1940708292;

	/**
	 * The reference instance of <code>members.isms_store_out</code>
	 */
	public static final IsmsStoreOut ISMS_STORE_OUT = new IsmsStoreOut();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsStoreOutRecord> getRecordType() {
		return IsmsStoreOutRecord.class;
	}

	/**
	 * The column <code>members.isms_store_out.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsStoreOutRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_store_out.store_out_no</code>. 出庫ID
	 */
	public final TableField<IsmsStoreOutRecord, Integer> STORE_OUT_NO = createField("store_out_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "出庫ID");

	/**
	 * The column <code>members.isms_store_out.data_ticket_no</code>. データ受渡票No
	 */
	public final TableField<IsmsStoreOutRecord, String> DATA_TICKET_NO = createField("data_ticket_no", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "データ受渡票No");

	/**
	 * The column <code>members.isms_store_out.out_date</code>. 出庫日
	 */
	public final TableField<IsmsStoreOutRecord, Timestamp> OUT_DATE = createField("out_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "出庫日");

	/**
	 * The column <code>members.isms_store_out.out_manager_id</code>. 出庫者
	 */
	public final TableField<IsmsStoreOutRecord, Integer> OUT_MANAGER_ID = createField("out_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "出庫者");

	/**
	 * The column <code>members.isms_store_out.destination</code>. 出庫先
	 */
	public final TableField<IsmsStoreOutRecord, String> DESTINATION = createField("destination", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "出庫先");

	/**
	 * The column <code>members.isms_store_out.out_approval_manager_id</code>. 出庫承認者
	 */
	public final TableField<IsmsStoreOutRecord, Integer> OUT_APPROVAL_MANAGER_ID = createField("out_approval_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "出庫承認者");

	/**
	 * Create a <code>members.isms_store_out</code> table reference
	 */
	public IsmsStoreOut() {
		this("isms_store_out", null);
	}

	/**
	 * Create an aliased <code>members.isms_store_out</code> table reference
	 */
	public IsmsStoreOut(String alias) {
		this(alias, ISMS_STORE_OUT);
	}

	private IsmsStoreOut(String alias, Table<IsmsStoreOutRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsStoreOut(String alias, Table<IsmsStoreOutRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "入出庫管理台帳出庫");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsStoreOutRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_STORE_OUT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsStoreOutRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsStoreOutRecord>>asList(Keys.KEY_ISMS_STORE_OUT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsStoreOut as(String alias) {
		return new IsmsStoreOut(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsStoreOut rename(String name) {
		return new IsmsStoreOut(name, null);
	}
}
