/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsOutsideMediaRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 保管管理簿
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsOutsideMedia extends TableImpl<IsmsOutsideMediaRecord> {

	private static final long serialVersionUID = -1025934020;

	/**
	 * The reference instance of <code>members.isms_outside_media</code>
	 */
	public static final IsmsOutsideMedia ISMS_OUTSIDE_MEDIA = new IsmsOutsideMedia();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsOutsideMediaRecord> getRecordType() {
		return IsmsOutsideMediaRecord.class;
	}

	/**
	 * The column <code>members.isms_outside_media.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsOutsideMediaRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_outside_media.outside_media_id</code>. 保管管理簿ID
	 */
	public final TableField<IsmsOutsideMediaRecord, Integer> OUTSIDE_MEDIA_ID = createField("outside_media_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "保管管理簿ID");

	/**
	 * The column <code>members.isms_outside_media.outside_media_no</code>. 保管管理簿番号
	 */
	public final TableField<IsmsOutsideMediaRecord, String> OUTSIDE_MEDIA_NO = createField("outside_media_no", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "保管管理簿番号");

	/**
	 * Create a <code>members.isms_outside_media</code> table reference
	 */
	public IsmsOutsideMedia() {
		this("isms_outside_media", null);
	}

	/**
	 * Create an aliased <code>members.isms_outside_media</code> table reference
	 */
	public IsmsOutsideMedia(String alias) {
		this(alias, ISMS_OUTSIDE_MEDIA);
	}

	private IsmsOutsideMedia(String alias, Table<IsmsOutsideMediaRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsOutsideMedia(String alias, Table<IsmsOutsideMediaRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "保管管理簿");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsOutsideMediaRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_OUTSIDE_MEDIA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsOutsideMediaRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsOutsideMediaRecord>>asList(Keys.KEY_ISMS_OUTSIDE_MEDIA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsOutsideMedia as(String alias) {
		return new IsmsOutsideMedia(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsOutsideMedia rename(String name) {
		return new IsmsOutsideMedia(name, null);
	}
}
