/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsStoreDisposeRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 入出庫管理台帳廃棄
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsStoreDispose extends TableImpl<IsmsStoreDisposeRecord> {

	private static final long serialVersionUID = 1798837595;

	/**
	 * The reference instance of <code>members.isms_store_dispose</code>
	 */
	public static final IsmsStoreDispose ISMS_STORE_DISPOSE = new IsmsStoreDispose();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsStoreDisposeRecord> getRecordType() {
		return IsmsStoreDisposeRecord.class;
	}

	/**
	 * The column <code>members.isms_store_dispose.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsStoreDisposeRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_store_dispose.store_dispose_no</code>. 廃棄ID
	 */
	public final TableField<IsmsStoreDisposeRecord, Integer> STORE_DISPOSE_NO = createField("store_dispose_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "廃棄ID");

	/**
	 * The column <code>members.isms_store_dispose.dispose_date</code>. 廃棄日
	 */
	public final TableField<IsmsStoreDisposeRecord, Timestamp> DISPOSE_DATE = createField("dispose_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "廃棄日");

	/**
	 * The column <code>members.isms_store_dispose.dispose_manager_id</code>. 廃棄者
	 */
	public final TableField<IsmsStoreDisposeRecord, Integer> DISPOSE_MANAGER_ID = createField("dispose_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "廃棄者");

	/**
	 * The column <code>members.isms_store_dispose.dispose_approval_manager_id</code>. 廃棄承認者
	 */
	public final TableField<IsmsStoreDisposeRecord, Integer> DISPOSE_APPROVAL_MANAGER_ID = createField("dispose_approval_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "廃棄承認者");

	/**
	 * Create a <code>members.isms_store_dispose</code> table reference
	 */
	public IsmsStoreDispose() {
		this("isms_store_dispose", null);
	}

	/**
	 * Create an aliased <code>members.isms_store_dispose</code> table reference
	 */
	public IsmsStoreDispose(String alias) {
		this(alias, ISMS_STORE_DISPOSE);
	}

	private IsmsStoreDispose(String alias, Table<IsmsStoreDisposeRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsStoreDispose(String alias, Table<IsmsStoreDisposeRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "入出庫管理台帳廃棄");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsStoreDisposeRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_STORE_DISPOSE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsStoreDisposeRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsStoreDisposeRecord>>asList(Keys.KEY_ISMS_STORE_DISPOSE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsStoreDispose as(String alias) {
		return new IsmsStoreDispose(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsStoreDispose rename(String name) {
		return new IsmsStoreDispose(name, null);
	}
}
