/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsStoreAssetRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 入出庫管理台帳資産管理
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsStoreAsset extends TableImpl<IsmsStoreAssetRecord> {

	private static final long serialVersionUID = 1912380996;

	/**
	 * The reference instance of <code>members.isms_store_asset</code>
	 */
	public static final IsmsStoreAsset ISMS_STORE_ASSET = new IsmsStoreAsset();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsStoreAssetRecord> getRecordType() {
		return IsmsStoreAssetRecord.class;
	}

	/**
	 * The column <code>members.isms_store_asset.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsStoreAssetRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_store_asset.pattern_id</code>. 分類ID
	 */
	public final TableField<IsmsStoreAssetRecord, Integer> PATTERN_ID = createField("pattern_id", org.jooq.impl.SQLDataType.INTEGER, this, "分類ID");

	/**
	 * The column <code>members.isms_store_asset.asset_manage_no</code>. 資産管理番号
	 */
	public final TableField<IsmsStoreAssetRecord, String> ASSET_MANAGE_NO = createField("asset_manage_no", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "資産管理番号");

	/**
	 * The column <code>members.isms_store_asset.span</code>. 保管期間
	 */
	public final TableField<IsmsStoreAssetRecord, String> SPAN = createField("span", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管期間");

	/**
	 * The column <code>members.isms_store_asset.destruction_method</code>. 破棄方法
	 */
	public final TableField<IsmsStoreAssetRecord, String> DESTRUCTION_METHOD = createField("destruction_method", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "破棄方法");

	/**
	 * The column <code>members.isms_store_asset.section</code>. 部門
	 */
	public final TableField<IsmsStoreAssetRecord, String> SECTION = createField("section", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "部門");

	/**
	 * The column <code>members.isms_store_asset.greater_manager_id</code>. 上位管理者
	 */
	public final TableField<IsmsStoreAssetRecord, Integer> GREATER_MANAGER_ID = createField("greater_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "上位管理者");

	/**
	 * The column <code>members.isms_store_asset.out_flg</code>. 出庫フラグ
	 */
	public final TableField<IsmsStoreAssetRecord, Integer> OUT_FLG = createField("out_flg", org.jooq.impl.SQLDataType.INTEGER, this, "出庫フラグ");

	/**
	 * The column <code>members.isms_store_asset.dispose_flg</code>. 廃棄フラグ
	 */
	public final TableField<IsmsStoreAssetRecord, Integer> DISPOSE_FLG = createField("dispose_flg", org.jooq.impl.SQLDataType.INTEGER, this, "廃棄フラグ");

	/**
	 * Create a <code>members.isms_store_asset</code> table reference
	 */
	public IsmsStoreAsset() {
		this("isms_store_asset", null);
	}

	/**
	 * Create an aliased <code>members.isms_store_asset</code> table reference
	 */
	public IsmsStoreAsset(String alias) {
		this(alias, ISMS_STORE_ASSET);
	}

	private IsmsStoreAsset(String alias, Table<IsmsStoreAssetRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsStoreAsset(String alias, Table<IsmsStoreAssetRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "入出庫管理台帳資産管理");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsStoreAssetRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_STORE_ASSET_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsStoreAssetRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsStoreAssetRecord>>asList(Keys.KEY_ISMS_STORE_ASSET_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsStoreAsset as(String alias) {
		return new IsmsStoreAsset(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsStoreAsset rename(String name) {
		return new IsmsStoreAsset(name, null);
	}
}
