/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsAssetAssessRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * アセスメント資産
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsAssetAssess extends TableImpl<IsmsAssetAssessRecord> {

	private static final long serialVersionUID = -1498337132;

	/**
	 * The reference instance of <code>members.isms_asset_assess</code>
	 */
	public static final IsmsAssetAssess ISMS_ASSET_ASSESS = new IsmsAssetAssess();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsAssetAssessRecord> getRecordType() {
		return IsmsAssetAssessRecord.class;
	}

	/**
	 * The column <code>members.isms_asset_assess.limit_date</code>. 締切日
	 */
	public final TableField<IsmsAssetAssessRecord, Timestamp> LIMIT_DATE = createField("limit_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "締切日");

	/**
	 * The column <code>members.isms_asset_assess.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsAssetAssessRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_asset_assess.pattern_id</code>. 分類ID
	 */
	public final TableField<IsmsAssetAssessRecord, Integer> PATTERN_ID = createField("pattern_id", org.jooq.impl.SQLDataType.INTEGER, this, "分類ID");

	/**
	 * The column <code>members.isms_asset_assess.asset_manage_no</code>. 資産管理番号
	 */
	public final TableField<IsmsAssetAssessRecord, String> ASSET_MANAGE_NO = createField("asset_manage_no", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "資産管理番号");

	/**
	 * The column <code>members.isms_asset_assess.asset_name</code>. 資産名
	 */
	public final TableField<IsmsAssetAssessRecord, String> ASSET_NAME = createField("asset_name", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "資産名");

	/**
	 * The column <code>members.isms_asset_assess.asset_type_id</code>. 保管形態ID
	 */
	public final TableField<IsmsAssetAssessRecord, Integer> ASSET_TYPE_ID = createField("asset_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "保管形態ID");

	/**
	 * The column <code>members.isms_asset_assess.place</code>. 保管場所
	 */
	public final TableField<IsmsAssetAssessRecord, String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管場所");

	/**
	 * The column <code>members.isms_asset_assess.span</code>. 保管期間
	 */
	public final TableField<IsmsAssetAssessRecord, String> SPAN = createField("span", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管期間");

	/**
	 * The column <code>members.isms_asset_assess.destruction_method</code>. 破棄方法
	 */
	public final TableField<IsmsAssetAssessRecord, String> DESTRUCTION_METHOD = createField("destruction_method", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "破棄方法");

	/**
	 * The column <code>members.isms_asset_assess.section</code>. 部門
	 */
	public final TableField<IsmsAssetAssessRecord, String> SECTION = createField("section", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "部門");

	/**
	 * The column <code>members.isms_asset_assess.manager_id</code>. 管理者
	 */
	public final TableField<IsmsAssetAssessRecord, Integer> MANAGER_ID = createField("manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "管理者");

	/**
	 * The column <code>members.isms_asset_assess.greater_manager_id</code>. 上位管理者
	 */
	public final TableField<IsmsAssetAssessRecord, Integer> GREATER_MANAGER_ID = createField("greater_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "上位管理者");

	/**
	 * The column <code>members.isms_asset_assess.remark</code>. 備考
	 */
	public final TableField<IsmsAssetAssessRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "備考");

	/**
	 * Create a <code>members.isms_asset_assess</code> table reference
	 */
	public IsmsAssetAssess() {
		this("isms_asset_assess", null);
	}

	/**
	 * Create an aliased <code>members.isms_asset_assess</code> table reference
	 */
	public IsmsAssetAssess(String alias) {
		this(alias, ISMS_ASSET_ASSESS);
	}

	private IsmsAssetAssess(String alias, Table<IsmsAssetAssessRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsAssetAssess(String alias, Table<IsmsAssetAssessRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "アセスメント資産");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsAssetAssessRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_ASSET_ASSESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsAssetAssessRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsAssetAssessRecord>>asList(Keys.KEY_ISMS_ASSET_ASSESS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsAssetAssess as(String alias) {
		return new IsmsAssetAssess(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsAssetAssess rename(String name) {
		return new IsmsAssetAssess(name, null);
	}
}
