/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsHardwareRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * ハードウェア台帳
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsHardware extends TableImpl<IsmsHardwareRecord> {

	private static final long serialVersionUID = -234010637;

	/**
	 * The reference instance of <code>members.isms_hardware</code>
	 */
	public static final IsmsHardware ISMS_HARDWARE = new IsmsHardware();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsHardwareRecord> getRecordType() {
		return IsmsHardwareRecord.class;
	}

	/**
	 * The column <code>members.isms_hardware.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsHardwareRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_hardware.hardware_manage_no</code>. ハードウェア管理番号
	 */
	public final TableField<IsmsHardwareRecord, String> HARDWARE_MANAGE_NO = createField("hardware_manage_no", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "ハードウェア管理番号");

	/**
	 * The column <code>members.isms_hardware.pattern_id</code>. 分類ID
	 */
	public final TableField<IsmsHardwareRecord, Integer> PATTERN_ID = createField("pattern_id", org.jooq.impl.SQLDataType.INTEGER, this, "分類ID");

	/**
	 * The column <code>members.isms_hardware.name</code>. 機種名
	 */
	public final TableField<IsmsHardwareRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "機種名");

	/**
	 * The column <code>members.isms_hardware.computer_name</code>. マシン名
	 */
	public final TableField<IsmsHardwareRecord, String> COMPUTER_NAME = createField("computer_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "マシン名");

	/**
	 * The column <code>members.isms_hardware.place</code>. 保管場所
	 */
	public final TableField<IsmsHardwareRecord, String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管場所");

	/**
	 * The column <code>members.isms_hardware.asset_type_id</code>. 保管形態ID
	 */
	public final TableField<IsmsHardwareRecord, Integer> ASSET_TYPE_ID = createField("asset_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "保管形態ID");

	/**
	 * The column <code>members.isms_hardware.span</code>. 保管期間
	 */
	public final TableField<IsmsHardwareRecord, String> SPAN = createField("span", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管期間");

	/**
	 * The column <code>members.isms_hardware.destruction_method</code>. 破棄方法
	 */
	public final TableField<IsmsHardwareRecord, String> DESTRUCTION_METHOD = createField("destruction_method", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "破棄方法");

	/**
	 * The column <code>members.isms_hardware.section</code>. 部門
	 */
	public final TableField<IsmsHardwareRecord, String> SECTION = createField("section", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "部門");

	/**
	 * The column <code>members.isms_hardware.manager_id</code>. 管理者ID
	 */
	public final TableField<IsmsHardwareRecord, Integer> MANAGER_ID = createField("manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "管理者ID");

	/**
	 * The column <code>members.isms_hardware.greater_manager_id</code>. 上位管理者ID
	 */
	public final TableField<IsmsHardwareRecord, Integer> GREATER_MANAGER_ID = createField("greater_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "上位管理者ID");

	/**
	 * The column <code>members.isms_hardware.remark</code>. 備考
	 */
	public final TableField<IsmsHardwareRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "備考");

	/**
	 * Create a <code>members.isms_hardware</code> table reference
	 */
	public IsmsHardware() {
		this("isms_hardware", null);
	}

	/**
	 * Create an aliased <code>members.isms_hardware</code> table reference
	 */
	public IsmsHardware(String alias) {
		this(alias, ISMS_HARDWARE);
	}

	private IsmsHardware(String alias, Table<IsmsHardwareRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsHardware(String alias, Table<IsmsHardwareRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "ハードウェア台帳");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsHardwareRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_HARDWARE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsHardwareRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsHardwareRecord>>asList(Keys.KEY_ISMS_HARDWARE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsHardware as(String alias) {
		return new IsmsHardware(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsHardware rename(String name) {
		return new IsmsHardware(name, null);
	}
}
