/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsManagePlanRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 管理策
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsManagePlan extends TableImpl<IsmsManagePlanRecord> {

	private static final long serialVersionUID = -1442953790;

	/**
	 * The reference instance of <code>members.isms_manage_plan</code>
	 */
	public static final IsmsManagePlan ISMS_MANAGE_PLAN = new IsmsManagePlan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsManagePlanRecord> getRecordType() {
		return IsmsManagePlanRecord.class;
	}

	/**
	 * The column <code>members.isms_manage_plan.manage_plan_id</code>. 管理策ID
	 */
	public final TableField<IsmsManagePlanRecord, Integer> MANAGE_PLAN_ID = createField("manage_plan_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "管理策ID");

	/**
	 * The column <code>members.isms_manage_plan.manage_item</code>. 箇条
	 */
	public final TableField<IsmsManagePlanRecord, String> MANAGE_ITEM = createField("manage_item", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "箇条");

	/**
	 * The column <code>members.isms_manage_plan.manage_item_name</code>. 項目名
	 */
	public final TableField<IsmsManagePlanRecord, String> MANAGE_ITEM_NAME = createField("manage_item_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "項目名");

	/**
	 * The column <code>members.isms_manage_plan.description</code>. 目的内容
	 */
	public final TableField<IsmsManagePlanRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "目的内容");

	/**
	 * The column <code>members.isms_manage_plan.used</code>. 適用可否
	 */
	public final TableField<IsmsManagePlanRecord, Integer> USED = createField("used", org.jooq.impl.SQLDataType.INTEGER, this, "適用可否");

	/**
	 * The column <code>members.isms_manage_plan.delete_flag</code>. 削除フラグ
	 */
	public final TableField<IsmsManagePlanRecord, Integer> DELETE_FLAG = createField("delete_flag", org.jooq.impl.SQLDataType.INTEGER, this, "削除フラグ");

	/**
	 * Create a <code>members.isms_manage_plan</code> table reference
	 */
	public IsmsManagePlan() {
		this("isms_manage_plan", null);
	}

	/**
	 * Create an aliased <code>members.isms_manage_plan</code> table reference
	 */
	public IsmsManagePlan(String alias) {
		this(alias, ISMS_MANAGE_PLAN);
	}

	private IsmsManagePlan(String alias, Table<IsmsManagePlanRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsManagePlan(String alias, Table<IsmsManagePlanRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "管理策");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsManagePlanRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_MANAGE_PLAN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsManagePlanRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsManagePlanRecord>>asList(Keys.KEY_ISMS_MANAGE_PLAN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsManagePlan as(String alias) {
		return new IsmsManagePlan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsManagePlan rename(String name) {
		return new IsmsManagePlan(name, null);
	}
}
