/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.IsmsVirtualMachineRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 仮想マシン台帳
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IsmsVirtualMachine extends TableImpl<IsmsVirtualMachineRecord> {

	private static final long serialVersionUID = 322274052;

	/**
	 * The reference instance of <code>members.isms_virtual_machine</code>
	 */
	public static final IsmsVirtualMachine ISMS_VIRTUAL_MACHINE = new IsmsVirtualMachine();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IsmsVirtualMachineRecord> getRecordType() {
		return IsmsVirtualMachineRecord.class;
	}

	/**
	 * The column <code>members.isms_virtual_machine.asset_id</code>. 資産ID
	 */
	public final TableField<IsmsVirtualMachineRecord, Long> ASSET_ID = createField("asset_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "資産ID");

	/**
	 * The column <code>members.isms_virtual_machine.virtual_machine_manage_no</code>. 仮想マシン管理番号
	 */
	public final TableField<IsmsVirtualMachineRecord, String> VIRTUAL_MACHINE_MANAGE_NO = createField("virtual_machine_manage_no", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "仮想マシン管理番号");

	/**
	 * The column <code>members.isms_virtual_machine.pattern_id</code>. 分類ID
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> PATTERN_ID = createField("pattern_id", org.jooq.impl.SQLDataType.INTEGER, this, "分類ID");

	/**
	 * The column <code>members.isms_virtual_machine.name</code>. 仮想マシン名
	 */
	public final TableField<IsmsVirtualMachineRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "仮想マシン名");

	/**
	 * The column <code>members.isms_virtual_machine.guest_name</code>. 仮想マシンゲスト名
	 */
	public final TableField<IsmsVirtualMachineRecord, String> GUEST_NAME = createField("guest_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "仮想マシンゲスト名");

	/**
	 * The column <code>members.isms_virtual_machine.stock_server_asset_id</code>. 保管サーバ名
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> STOCK_SERVER_ASSET_ID = createField("stock_server_asset_id", org.jooq.impl.SQLDataType.INTEGER, this, "保管サーバ名");

	/**
	 * The column <code>members.isms_virtual_machine.stock_place</code>. 保管場所
	 */
	public final TableField<IsmsVirtualMachineRecord, String> STOCK_PLACE = createField("stock_place", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管場所");

	/**
	 * The column <code>members.isms_virtual_machine.asset_type_id</code>. 保管形態ID
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> ASSET_TYPE_ID = createField("asset_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "保管形態ID");

	/**
	 * The column <code>members.isms_virtual_machine.span</code>. 保管期間
	 */
	public final TableField<IsmsVirtualMachineRecord, String> SPAN = createField("span", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "保管期間");

	/**
	 * The column <code>members.isms_virtual_machine.destruction_method</code>. 破棄方法
	 */
	public final TableField<IsmsVirtualMachineRecord, String> DESTRUCTION_METHOD = createField("destruction_method", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "破棄方法");

	/**
	 * The column <code>members.isms_virtual_machine.section</code>. 部門
	 */
	public final TableField<IsmsVirtualMachineRecord, String> SECTION = createField("section", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "部門");

	/**
	 * The column <code>members.isms_virtual_machine.manager_id</code>. 管理者ID
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> MANAGER_ID = createField("manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "管理者ID");

	/**
	 * The column <code>members.isms_virtual_machine.greater_manager_id</code>. 上位管理者ID
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> GREATER_MANAGER_ID = createField("greater_manager_id", org.jooq.impl.SQLDataType.INTEGER, this, "上位管理者ID");

	/**
	 * The column <code>members.isms_virtual_machine.capacity</code>. 容量
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> CAPACITY = createField("capacity", org.jooq.impl.SQLDataType.INTEGER, this, "容量");

	/**
	 * The column <code>members.isms_virtual_machine.memory_size</code>. メモリサイズ
	 */
	public final TableField<IsmsVirtualMachineRecord, Integer> MEMORY_SIZE = createField("memory_size", org.jooq.impl.SQLDataType.INTEGER, this, "メモリサイズ");

	/**
	 * The column <code>members.isms_virtual_machine.remark</code>. 備考
	 */
	public final TableField<IsmsVirtualMachineRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "備考");

	/**
	 * Create a <code>members.isms_virtual_machine</code> table reference
	 */
	public IsmsVirtualMachine() {
		this("isms_virtual_machine", null);
	}

	/**
	 * Create an aliased <code>members.isms_virtual_machine</code> table reference
	 */
	public IsmsVirtualMachine(String alias) {
		this(alias, ISMS_VIRTUAL_MACHINE);
	}

	private IsmsVirtualMachine(String alias, Table<IsmsVirtualMachineRecord> aliased) {
		this(alias, aliased, null);
	}

	private IsmsVirtualMachine(String alias, Table<IsmsVirtualMachineRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "仮想マシン台帳");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IsmsVirtualMachineRecord> getPrimaryKey() {
		return Keys.KEY_ISMS_VIRTUAL_MACHINE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IsmsVirtualMachineRecord>> getKeys() {
		return Arrays.<UniqueKey<IsmsVirtualMachineRecord>>asList(Keys.KEY_ISMS_VIRTUAL_MACHINE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IsmsVirtualMachine as(String alias) {
		return new IsmsVirtualMachine(alias, this);
	}

	/**
	 * Rename this table
	 */
	public IsmsVirtualMachine rename(String name) {
		return new IsmsVirtualMachine(name, null);
	}
}
