/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.PersonalSkillRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 個人スキル
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalSkill extends TableImpl<PersonalSkillRecord> {

	private static final long serialVersionUID = 1508790361;

	/**
	 * The reference instance of <code>members.personal_skill</code>
	 */
	public static final PersonalSkill PERSONAL_SKILL = new PersonalSkill();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PersonalSkillRecord> getRecordType() {
		return PersonalSkillRecord.class;
	}

	/**
	 * The column <code>members.personal_skill.user_id</code>. ユーザID
	 */
	public final TableField<PersonalSkillRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "ユーザID");

	/**
	 * The column <code>members.personal_skill.skill_type_no</code>. スキル種類番号
	 */
	public final TableField<PersonalSkillRecord, Integer> SKILL_TYPE_NO = createField("skill_type_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "スキル種類番号");

	/**
	 * The column <code>members.personal_skill.skill_no</code>. スキル番号
	 */
	public final TableField<PersonalSkillRecord, Integer> SKILL_NO = createField("skill_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "スキル番号");

	/**
	 * The column <code>members.personal_skill.comment</code>. コメント
	 */
	public final TableField<PersonalSkillRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "コメント");

	/**
	 * The column <code>members.personal_skill.created</code>. 登録日時
	 */
	public final TableField<PersonalSkillRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "登録日時");

	/**
	 * The column <code>members.personal_skill.created_user</code>. 登録ユーザ
	 */
	public final TableField<PersonalSkillRecord, Integer> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.INTEGER, this, "登録ユーザ");

	/**
	 * The column <code>members.personal_skill.updated</code>. 更新日時
	 */
	public final TableField<PersonalSkillRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新日時");

	/**
	 * The column <code>members.personal_skill.updated_user</code>. 更新ユーザ
	 */
	public final TableField<PersonalSkillRecord, Integer> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.INTEGER, this, "更新ユーザ");

	/**
	 * The column <code>members.personal_skill.deleted</code>. 削除日時
	 */
	public final TableField<PersonalSkillRecord, Timestamp> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TIMESTAMP, this, "削除日時");

	/**
	 * The column <code>members.personal_skill.deleted_user</code>. 削除ユーザ
	 */
	public final TableField<PersonalSkillRecord, Integer> DELETED_USER = createField("deleted_user", org.jooq.impl.SQLDataType.INTEGER, this, "削除ユーザ");

	/**
	 * The column <code>members.personal_skill.version</code>. バージョン
	 */
	public final TableField<PersonalSkillRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "バージョン");

	/**
	 * Create a <code>members.personal_skill</code> table reference
	 */
	public PersonalSkill() {
		this("personal_skill", null);
	}

	/**
	 * Create an aliased <code>members.personal_skill</code> table reference
	 */
	public PersonalSkill(String alias) {
		this(alias, PERSONAL_SKILL);
	}

	private PersonalSkill(String alias, Table<PersonalSkillRecord> aliased) {
		this(alias, aliased, null);
	}

	private PersonalSkill(String alias, Table<PersonalSkillRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "個人スキル");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PersonalSkillRecord> getPrimaryKey() {
		return Keys.KEY_PERSONAL_SKILL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PersonalSkillRecord>> getKeys() {
		return Arrays.<UniqueKey<PersonalSkillRecord>>asList(Keys.KEY_PERSONAL_SKILL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<PersonalSkillRecord, Integer> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonalSkill as(String alias) {
		return new PersonalSkill(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PersonalSkill rename(String name) {
		return new PersonalSkill(name, null);
	}
}
