/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.TopMessageRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * メッセージ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TopMessage extends TableImpl<TopMessageRecord> {

	private static final long serialVersionUID = -277228047;

	/**
	 * The reference instance of <code>members.top_message</code>
	 */
	public static final TopMessage TOP_MESSAGE = new TopMessage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TopMessageRecord> getRecordType() {
		return TopMessageRecord.class;
	}

	/**
	 * The column <code>members.top_message.message_id</code>. メッセージID
	 */
	public final TableField<TopMessageRecord, Long> MESSAGE_ID = createField("message_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "メッセージID");

	/**
	 * The column <code>members.top_message.message_date</code>. メッセージ日付
	 */
	public final TableField<TopMessageRecord, Timestamp> MESSAGE_DATE = createField("message_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "メッセージ日付");

	/**
	 * The column <code>members.top_message.content</code>. メッセージ内容
	 */
	public final TableField<TopMessageRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "メッセージ内容");

	/**
	 * The column <code>members.top_message.sort_order</code>. 並び順
	 */
	public final TableField<TopMessageRecord, Long> SORT_ORDER = createField("sort_order", org.jooq.impl.SQLDataType.BIGINT, this, "並び順");

	/**
	 * The column <code>members.top_message.created</code>. 登録日時
	 */
	public final TableField<TopMessageRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "登録日時");

	/**
	 * The column <code>members.top_message.created_user</code>. 登録ユーザ
	 */
	public final TableField<TopMessageRecord, Integer> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.INTEGER, this, "登録ユーザ");

	/**
	 * The column <code>members.top_message.updated</code>. 更新日時
	 */
	public final TableField<TopMessageRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新日時");

	/**
	 * The column <code>members.top_message.updated_user</code>. 更新ユーザ
	 */
	public final TableField<TopMessageRecord, Integer> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.INTEGER, this, "更新ユーザ");

	/**
	 * The column <code>members.top_message.deleted</code>. 削除日時
	 */
	public final TableField<TopMessageRecord, Timestamp> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TIMESTAMP, this, "削除日時");

	/**
	 * The column <code>members.top_message.deleted_user</code>. 削除ユーザ
	 */
	public final TableField<TopMessageRecord, Integer> DELETED_USER = createField("deleted_user", org.jooq.impl.SQLDataType.INTEGER, this, "削除ユーザ");

	/**
	 * The column <code>members.top_message.version</code>. バージョン
	 */
	public final TableField<TopMessageRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "バージョン");

	/**
	 * Create a <code>members.top_message</code> table reference
	 */
	public TopMessage() {
		this("top_message", null);
	}

	/**
	 * Create an aliased <code>members.top_message</code> table reference
	 */
	public TopMessage(String alias) {
		this(alias, TOP_MESSAGE);
	}

	private TopMessage(String alias, Table<TopMessageRecord> aliased) {
		this(alias, aliased, null);
	}

	private TopMessage(String alias, Table<TopMessageRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "メッセージ");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TopMessageRecord> getPrimaryKey() {
		return Keys.KEY_TOP_MESSAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TopMessageRecord>> getKeys() {
		return Arrays.<UniqueKey<TopMessageRecord>>asList(Keys.KEY_TOP_MESSAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<TopMessageRecord, Integer> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TopMessage as(String alias) {
		return new TopMessage(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TopMessage rename(String name) {
		return new TopMessage(name, null);
	}
}
