/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.UserAuthRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * ユーザ権限
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAuth extends TableImpl<UserAuthRecord> {

	private static final long serialVersionUID = 73069664;

	/**
	 * The reference instance of <code>members.user_auth</code>
	 */
	public static final UserAuth USER_AUTH = new UserAuth();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserAuthRecord> getRecordType() {
		return UserAuthRecord.class;
	}

	/**
	 * The column <code>members.user_auth.user_id</code>. ユーザID
	 */
	public final TableField<UserAuthRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "ユーザID");

	/**
	 * The column <code>members.user_auth.auth_cd1</code>. 権限コード1
	 */
	public final TableField<UserAuthRecord, String> AUTH_CD1 = createField("auth_cd1", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "権限コード1");

	/**
	 * The column <code>members.user_auth.auth_cd2</code>. 権限コード2
	 */
	public final TableField<UserAuthRecord, String> AUTH_CD2 = createField("auth_cd2", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "権限コード2");

	/**
	 * The column <code>members.user_auth.auth_cd3</code>. 権限コード3
	 */
	public final TableField<UserAuthRecord, String> AUTH_CD3 = createField("auth_cd3", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "権限コード3");

	/**
	 * The column <code>members.user_auth.auth_cd4</code>. 権限コード4
	 */
	public final TableField<UserAuthRecord, String> AUTH_CD4 = createField("auth_cd4", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "権限コード4");

	/**
	 * The column <code>members.user_auth.auth_cd5</code>. 権限コード5
	 */
	public final TableField<UserAuthRecord, String> AUTH_CD5 = createField("auth_cd5", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "権限コード5");

	/**
	 * The column <code>members.user_auth.version</code>. バージョン
	 */
	public final TableField<UserAuthRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "バージョン");

	/**
	 * Create a <code>members.user_auth</code> table reference
	 */
	public UserAuth() {
		this("user_auth", null);
	}

	/**
	 * Create an aliased <code>members.user_auth</code> table reference
	 */
	public UserAuth(String alias) {
		this(alias, USER_AUTH);
	}

	private UserAuth(String alias, Table<UserAuthRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserAuth(String alias, Table<UserAuthRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "ユーザ権限");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserAuthRecord> getPrimaryKey() {
		return Keys.KEY_USER_AUTH_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserAuthRecord>> getKeys() {
		return Arrays.<UniqueKey<UserAuthRecord>>asList(Keys.KEY_USER_AUTH_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<UserAuthRecord, Integer> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserAuth as(String alias) {
		return new UserAuth(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserAuth rename(String name) {
		return new UserAuth(name, null);
	}
}
