/**
 * This class is generated by jOOQ
 */
package jp.co.kunisys.member.query.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jp.co.kunisys.member.query.Keys;
import jp.co.kunisys.member.query.Members;
import jp.co.kunisys.member.query.tables.records.UserInfoRetireRecord;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 退職情報
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRetire extends TableImpl<UserInfoRetireRecord> {

	private static final long serialVersionUID = -1098911098;

	/**
	 * The reference instance of <code>members.user_info_retire</code>
	 */
	public static final UserInfoRetire USER_INFO_RETIRE = new UserInfoRetire();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserInfoRetireRecord> getRecordType() {
		return UserInfoRetireRecord.class;
	}

	/**
	 * The column <code>members.user_info_retire.user_id</code>. ユーザID
	 */
	public final TableField<UserInfoRetireRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "ユーザID");

	/**
	 * The column <code>members.user_info_retire.retire_type</code>. 退職区分
	 */
	public final TableField<UserInfoRetireRecord, String> RETIRE_TYPE = createField("retire_type", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "退職区分");

	/**
	 * The column <code>members.user_info_retire.retire_date</code>. 退職日
	 */
	public final TableField<UserInfoRetireRecord, Date> RETIRE_DATE = createField("retire_date", org.jooq.impl.SQLDataType.DATE, this, "退職日");

	/**
	 * The column <code>members.user_info_retire.created</code>. 登録日時
	 */
	public final TableField<UserInfoRetireRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "登録日時");

	/**
	 * The column <code>members.user_info_retire.created_user</code>. 登録ユーザ
	 */
	public final TableField<UserInfoRetireRecord, Integer> CREATED_USER = createField("created_user", org.jooq.impl.SQLDataType.INTEGER, this, "登録ユーザ");

	/**
	 * The column <code>members.user_info_retire.updated</code>. 更新日時
	 */
	public final TableField<UserInfoRetireRecord, Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新日時");

	/**
	 * The column <code>members.user_info_retire.updated_user</code>. 更新ユーザ
	 */
	public final TableField<UserInfoRetireRecord, Integer> UPDATED_USER = createField("updated_user", org.jooq.impl.SQLDataType.INTEGER, this, "更新ユーザ");

	/**
	 * The column <code>members.user_info_retire.deleted</code>. 削除日時
	 */
	public final TableField<UserInfoRetireRecord, Timestamp> DELETED = createField("deleted", org.jooq.impl.SQLDataType.TIMESTAMP, this, "削除日時");

	/**
	 * The column <code>members.user_info_retire.deleted_user</code>. 削除ユーザ
	 */
	public final TableField<UserInfoRetireRecord, Integer> DELETED_USER = createField("deleted_user", org.jooq.impl.SQLDataType.INTEGER, this, "削除ユーザ");

	/**
	 * The column <code>members.user_info_retire.version</code>. バージョン
	 */
	public final TableField<UserInfoRetireRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "バージョン");

	/**
	 * Create a <code>members.user_info_retire</code> table reference
	 */
	public UserInfoRetire() {
		this("user_info_retire", null);
	}

	/**
	 * Create an aliased <code>members.user_info_retire</code> table reference
	 */
	public UserInfoRetire(String alias) {
		this(alias, USER_INFO_RETIRE);
	}

	private UserInfoRetire(String alias, Table<UserInfoRetireRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserInfoRetire(String alias, Table<UserInfoRetireRecord> aliased, Field<?>[] parameters) {
		super(alias, Members.MEMBERS, aliased, parameters, "退職情報");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserInfoRetireRecord> getPrimaryKey() {
		return Keys.KEY_USER_INFO_RETIRE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserInfoRetireRecord>> getKeys() {
		return Arrays.<UniqueKey<UserInfoRetireRecord>>asList(Keys.KEY_USER_INFO_RETIRE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TableField<UserInfoRetireRecord, Integer> getRecordVersion() {
		return VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserInfoRetire as(String alias) {
		return new UserInfoRetire(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserInfoRetire rename(String name) {
		return new UserInfoRetire(name, null);
	}
}
